### PR TITLE
[Clang][SYCL] Fix dangling pointers and ODR violation in free functions

### PR DESCRIPTION
**Pull request by uditagarwal97**
**Problems**
Problem 1: When a library consisting of free function kernels is registered with SYCL RT, we store pointers (as `string_view`) to free function names in `m_FreeFunctionKernelGlobalInfo` but we do not remove them from `m_FreeFunctionKernelGlobalInfo` when the library is unloaded. Thus, we end up holding dangling pointers and any further operation on `m_FreeFunctionKernelGlobalInfo` might segfault.

Problem 2: Consider the case when you have multiple TUs with free functions and they are compiled separately but linked together into a single shared lib. In that case, we will have multiple definition of `static GlobalMapUpdater updater` in the shared lib => violating ODR

**Solution**
Discard pointers to free function names when library is unloaded and have `GlobalMapUpdater` defined in anonymous namespace, instead of `sycl::v1::detail`

### CODE REVIEW

File: sycl/source/detail/program_manager/program_manager.hpp [hunk 1]
```diff
@@ -259,6 +259,12 @@ class ProgramManager {
   void registerKernelGlobalInfo(
       std::unordered_map<std::string_view, unsigned> &&GlobalInfoToCopy);
 
+  // The function removes kernel global descriptors from the
+  // kernel global map when a shared library consisting o SYCL kernels
+  // is unloaded.
```
Comment (aelovikov-intel) [inline sycl/source/detail/program_manager/program_manager.hpp]:
```suggestion
  // kernel global map when a shared library consisting of SYCL kernels
  // is unloaded.
```

File: sycl/test/abi/sycl_symbols_linux.dump [hunk 2]
```diff
@@ -2985,12 +2985,12 @@ _ZN4sycl3_V121__isgreaterequal_implEdd
 _ZN4sycl3_V121__isgreaterequal_implEff
 _ZN4sycl3_V122accelerator_selector_vERKNS0_6deviceE
 _ZN4sycl3_V128verifyUSMAllocatorPropertiesERKNS0_13property_listE
-_ZN4sycl3_V139submit_kernel_direct_without_event_implILi1EEEvRKNS0_5queueERKNS0_8nd_rangeIXT_EEERNS0_6detail17HostKernelRefBaseEPNS9_16DeviceKernelInfoERKNS9_13code_locationEb
 _ZN4sycl3_V136submit_kernel_direct_with_event_implILi1EEENS0_5eventERKNS0_5queueERKNS0_8nd_rangeIXT_EEERNS0_6detail17HostKernelRefBaseEPNSA_16DeviceKernelInfoERKNSA_13code_locationEb
+_ZN4sycl3_V136submit_kernel_direct_with_event_implILi2EEENS0_5eventERKNS0_5queueERKNS0_8nd_rangeIXT_EEERNS0_6detail17HostKernelRefBaseEPNSA_16DeviceKernelInfoERKNSA_13code_locationEb
 _ZN4sycl3_V136submit_kernel_direct_with_event_implILi3EEENS0_5eventERKNS0_5queueERKNS0_8nd_rangeIXT_EEERNS0_6detail17HostKernelRefBaseEPNSA_16DeviceKernelInfoERKNSA_13code_locationEb
+_ZN4sycl3_V139submit_kernel_direct_without_event_implILi1EEEvRKNS0_5queueERKNS0_8nd_rangeIXT_EEERNS0_6detail17HostKernelRefBaseEPNS9_16DeviceKernelInfoERKNS9_13code_locationEb
```
Comment (aelovikov-intel) [inline sycl/test/abi/sycl_symbols_linux.dump:2991]: Please drop unnecessary changes.

**Review by elizabethandrews — APPROVED** [review]

**Comment by cperkinsintel** [comment]
Should this have an E2E test?  Though it's possible that this is already exercised by some of the IntermediateLib tests ( https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/IntermediateLib/multi_lib_app.cpp )

**Comment by uditagarwal97** [comment]
> Should this have an E2E test? Though it's possible that this is already exercised by some of the IntermediateLib tests ( https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/IntermediateLib/multi_lib_app.cpp )

@cperkinsintel I'm finding it hard to reproduce the dangling pointer bug using an E2E/LIT test, although it's easily reproducible using valgrind. The rest of the code changes in this PR can be tested by existing FreeFunction tests.

**Comment by uditagarwal97** [comment]
Along with dangling pointers, there's another bug in current FreeFunction implementation.
It's due to violation of ODR because of multiple definitions of `static GlobalMapUpdater updater`, which can happen when you have multiple TU with free functions and they are compiled separately but linked together into a single shared lib.
To fix this bug, in https://github.com/intel/llvm/pull/20422/commits/2079eb28d067d9bf80c6c9f61c0546cbef4c149e commit, I have moved `GlobalMapUpdater` into an anonymous namespace instead of `sycl::v1::detail`.

**Review by cperkinsintel — APPROVED** [review]

**Comment by uditagarwal97** [comment]
@elizabethandrews (@intel/dpcpp-cfe-reviewers) Can you please re-review the FE changes? I made a minor change (https://github.com/intel/llvm/pull/20422/commits/2079eb28d067d9bf80c6c9f61c0546cbef4c149e) since the last review. Thanks!

**Review by dklochkov-emb — APPROVED** [review]

File: clang/lib/Sema/SemaSYCL.cpp [hunk 3]
```diff
@@ -7302,22 +7302,30 @@ void SYCLIntegrationHeader::emit(raw_ostream &O) {
...
+    O << "    sycl::detail::free_function_info_map::remove("
+      << "sycl::detail::kernel_names, sycl::detail::kernel_args_sizes, "
+      << KernelDescs.size() << ");\n";
+    O << "  }\n";
     O << "};\n";
     O << "static GlobalMapUpdater updater;\n";
-    O << "} // namespace detail\n";
-    O << "} // namespace _V1\n";
-    O << "} // namespace sycl\n";
+    O << "} //\n";
```
Comment (premanandrao) [inline clang/lib/Sema/SemaSYCL.cpp]:
```suggestion
    O << "} // namespace\n";
```

File: clang/test/SemaSYCL/Inputs/sycl/detail/kernel_global_info.hpp [hunk 4]
```diff
@@ -10,14 +10,11 @@
...
 #include <sycl/detail/export.hpp>
 
-namespace sycl {
-inline namespace _V1 {
-namespace detail {
+namespace {
 namespace free_function_info_map {
 
 __SYCL_EXPORT void add(const void *DeviceGlobalPtr, const char *UniqueId);
+__SYCL_EXPORT void remove(const void *DeviceGlobalPtr, const char *UniqueId);
```
Comment (premanandrao) [inline clang/test/SemaSYCL/Inputs/sycl/detail/kernel_global_info.hpp:17]: Were the changes in this file needed?   (I understand it is the mock header, but I don't see this tested in SemaSYCL anywhere.)

Comment (uditagarwal97) [reply clang/test/SemaSYCL/Inputs/sycl/detail/kernel_global_info.hpp:17]: @dklochkov-emb since this file was added in https://github.com/intel/llvm/pull/19517/files#diff-dfac134a49adec0ea0525b0941ce5b5e8b51c64e0692aae6c8f0105b9936106e, do you know how is it being used?

Comment (dklochkov-emb) [reply clang/test/SemaSYCL/Inputs/sycl/detail/kernel_global_info.hpp:17]: as far as I know it is needed for SemaSYCL tests, i.e. it mocks real header. For example, test file
https://github.com/intel/llvm/blob/sycl/clang/test/SemaSYCL/free_function_kernel_params.cpp
 
contains `-internal-isystem %S/Inputs`. In my understanding, this file will be visible to include as the system file after that
