### ISSUE TITLE
[SYCL] Sema sycl-dllimport-dllexport test failed after community changes

### ISSUE THREAD

**Issue by vmaksimo** [intel/llvm#2758]
The issue is found during the pulldown (PR https://github.com/intel/llvm/pull/2745), regression is caused by ff2e24a.
Looks like we expect dllexport/dllimport attributes to be not supported, but they are just ignored as unknown ones.

```
/localdisk2/sycl_ci/buildbot/worker/sycl-ubu-x64-pr/llvm.src/clang/test/SemaSYCL/sycl-dllimport-dllexport.cpp:22:11: error: CHECK: expected string not found in input
// CHECK: warning: __declspec attribute 'dllexport' is not supported
          ^
<stdin>:1:1: note: scanning from here
/localdisk2/sycl_ci/buildbot/worker/sycl-ubu-x64-pr/llvm.src/clang/test/SemaSYCL/sycl-dllimport-dllexport.cpp:32:7: warning: unknown attribute 'dllimport' ignored [-Wunknown-attributes]
^
<stdin>:1:117: note: possible intended match here
/localdisk2/sycl_ci/buildbot/worker/sycl-ubu-x64-pr/llvm.src/clang/test/SemaSYCL/sycl-dllimport-dllexport.cpp:32:7: warning: unknown attribute 'dllimport' ignored [-Wunknown-attributes]
```
Surprisingly, it failed on both Linux and Win, although the change seems to have support of these attributes on Windows.
I'll mark the test with XFAIL until further fix.
