### PR TITLE
[SYCL] Support build with shared libzstd

### LINKED ISSUE #22310: sycl: zstd_STATIC_LIBRARY is NOTFOUND building on almalinux 8
### Describe the bug

We are working to support Pytorch CI with intel/llvm compiler, see https://github.com/intel/torch-xpu-ops/pull/3934. Pytorch build is done on almalinux 8 (RHEL 8 derivative) and requires support for `--offload-compress` which depends on ZSTD library. The `libzstd` library on Fedora family is available only as a shared library. Building against system installed dependencies is a strong requirement within Linux ecosystem especially for Linux distro packaging of the components. The build of intel/llvm compiler is failing on such setup because SYCL library configuration mistakenly relies only on static ZSTD library:
https://github.com/intel/llvm/blob/b09acde14f87bb417d5868905a684263beb32991/sycl/source/CMakeLists.txt#L176

Compare with how similar places implemented in other places in LLVM:
https://github.com/intel/llvm/blob/b09acde14f87bb417d5868905a684263beb32991/llvm/lib/Support/CMakeLists.txt#L28-L38

and:
https://github.com/intel/llvm/blob/b09acde14f87bb417d5868905a684263beb32991/lld/ELF/CMakeLists.txt#L9-L18

### To reproduce

```
$ docker pull pytorch/manylinux2_28-builder:xpu-main
$ docker run -it --rm -v $(pwd):/opt/_llvm pytorch/manylinux2_28-builder:xpu-main
# /opt/python/cp314-cp314/bin/python3 -m venv /opt/_build
# . /opt/_build/bin/activate
# pip install cmake ninja
# dnf install -y libtool libzstd-devel
# cmake -B build -S llvm -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
    -DBUILD_SHARED_LIBS=ON \
    -DLLVM_BUILD_TOOLS=ON \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_ENABLE_DOXYGEN=OFF \
    -DLLVM_ENABLE_LLD=OFF \
    -DLLVM_ENABLE_PROJECTS='clang;sycl;llvm-spirv;opencl;xpti;xptifw;compiler-rt;libdevice;sycl-jit' \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_ENABLE_SPHINX=OFF \
    -DLLVM_ENABLE_ZSTD=ON \
    -DLLVM_EXTERNAL_PROJECTS='sycl;llvm-spirv;opencl;xpti;xptifw;compiler-rt;libdevice;sycl-jit' \
    -DLLVM_SPIRV_ENABLE_LIBSPIRV_DIS=OFF \
    -DLLVM_TARGETS_TO_BUILD='host;SPIRV' \
    -DSYCL_ENABLE_EXTENSION_JIT=ON \
    -DSYCL_ENABLE_MAJOR_RELEASE_PREVIEW_LIB=OFF \
    -DSYCL_ENABLE_WERROR=OFF \
    -DSYCL_ENABLE_XPTI_TRACING=ON \
    -DLLVM_EXTERNAL_LIBDEVICE_SOURCE_DIR=$(pwd)/libdevice \
    -DLLVM_EXTERNAL_LLVM_SPIRV_SOURCE_DIR=$(pwd)/llvm-spirv \
    -DLLVM_EXTERNAL_SYCL_JIT_SOURCE_DIR=$(pwd)/sycl-jit \
    -DLLVM_EXTERNAL_SYCL_SOURCE_DIR=$(pwd)/sycl \
    -DLLVM_EXTERNAL_XPTI_SOURCE_DIR=$(pwd)/xpti \
    -DLLVM_EXTERNAL_XPTIFW_SOURCE_DIR=$(pwd)/xptifw \
    -DSYCL_INCLUDE_TESTS=OFF \
    -DXPTI_ENABLE_WERROR=OFF
<...>
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
zstd_STATIC_LIBRARY (ADVANCED)
    linked by target "sycl" in directory /opt/_llvm/sycl/source

-- Generating done (5.3s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### Environment

- OS: Linux
- DPC++ version: https://github.com/intel/llvm/commit/b09acde14f87bb417d5868905a684263beb32991 (latest main as of 6/12/2026)

### Additional context

* Proposed fix to align with LLVM behavior: https://github.com/intel/llvm/pull/22294

CC: @sarnex, @uditagarwal97

### PR DESCRIPTION
**Pull request by dvrogozh**
Distros of Fedora family package only shared libzstd build against which was not fully supported. This commit addresses the gap in a similar way as it's already handled in few other cases in llvm. See for reference:
https://github.com/intel/llvm/blob/b09acde14f87bb417d5868905a684263beb32991/llvm/lib/Support/CMakeLists.txt#L28-L38

and:
https://github.com/intel/llvm/blob/b09acde14f87bb417d5868905a684263beb32991/lld/ELF/CMakeLists.txt#L9-L18

Fixes: https://github.com/intel/llvm/issues/22310

CC: @sarnex

### CODE REVIEW

**Comment by sarnex** [comment]
@uditagarwal97 Do you mind handling the review of this one? I remember you worked on the zstd support and there was some weird behavior requiring us to use the static one for reasons I don't totally remember. Thanks!

**Comment by uditagarwal97** [comment]
@dvrogozh The reason why we only supported building DPCPP with static zstd initially was to ease distribution of DPCPP by not requiring customers to install zstd separately (if we would have used shared zstd library). While installing zstd on Linux is trivial, that's not the case on Windows. So, in this PR, please put shared zstd build behind a flag that user can opt-in so that the default DPCPP build remains the same.

**Comment by dvrogozh** [comment]
> So, in this PR, please put shared zstd build behind a flag that user can opt-in so that the default DPCPP build remains the same.

Such flag already exists and is inherited from original vllm - that's `LLVM_USE_STATIC_ZSTD`. This PR does not change current behavior, but just fixes the issue for the build path when user opts-in for the shared zstd. By default the build script for the compiler forces static zstd already:
https://github.com/intel/llvm/blob/75612946c7d50262d4da968b9c11895c1e6e6e4b/buildbot/configure.py#L185

**Comment by uditagarwal97** [comment]
> > So, in this PR, please put shared zstd build behind a flag that user can opt-in so that the default DPCPP build remains the same.
> 
> Such flag already exists and is inherited from original vllm - that's `LLVM_USE_STATIC_ZSTD`. This PR does not change current behavior, but just fixes the issue for the build path when user opts-in for the shared zstd. By default the build script for the compiler forces static zstd already:
> 
> https://github.com/intel/llvm/blob/75612946c7d50262d4da968b9c11895c1e6e6e4b/buildbot/configure.py#L185

I don't think we can rely on `LLVM_USE_STATIC_ZSTD` because it is not enabled by default and not of all DPCPP users use the `buildbot/configure.py` script. Can we have another CMake flag or maybe do something like the following in `sycl/CMakeFile`:
```
#ifndef LLVM_USE_STATIC_ZSTD
#define LLVM_USE_STATIC_ZSTD 1
#endif

#if LLVM_USE_STATIC_ZSTD 
// Use static zstd
#else
// Use shared
#endif
```
And for Fedora build you can explicitly pass -DLLVM_USE_STATIC_ZSTD=0.

**Comment by dvrogozh** [comment]
> I don't think we can rely on LLVM_USE_STATIC_ZSTD because it is not enabled by default and not of all DPCPP users use the buildbot/configure.py script. Can we have another CMake flag <...>

@uditagarwal97, this seem to reinvent the wheel. `LLVM_USE_STATIC_ZSTD` is a standard flag available and well established in LLVM. Why it is suddenly not enough for the derivative DPC++ compiler? It gives a full control to the user already. As I pointed out, those users who are using `buildbot/configure.py` already are on a static zstd path as it's hardcoded in the script. Those who are using cmake directly already have all the control they need thru the flags exposed by LLVM. I would also argue about the "default" behavior. What is that exactly? Note that the only documented way to build DPC++ compiler is thru `buildbot/configure.py` which makes everything else including direct usage of cmake non-default.

**Comment by uditagarwal97** [comment]
> I would also argue about the "default" behavior. What is that exactly?

Even if the user doesn't set `LLVM_USE_STATIC_ZSTD`, the current DPCPP build always links zstd static library. But, after your PR, that behavior will change and now it will start linking against shared zstd library, if it is available. The consequence of it will be severe - we will end up **unintentionally** introducing a runtime dependency to DPCPP.

So, what are our options?
(1) Ask all DPCPP customers who build DPCPP from source to change their existing build scripts and add `-DLLVM_USE_STATIC_ZSTD` flag while configuring DPCPP
(2) Set `LLVM_USE_STATIC_ZSTD=1` by default while allowing user to override it if they intentionally want to have zstd as a runtime dependency of DPCPP.

Which of these options do you think will be most comfortable for our customers?

Regarding `buildbot/configure.py` script, here's what our documentation (https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#build-dpc-toolchain) says:

> Note that the CMake variables set by default by the [configure.py](https://github.com/intel/llvm/blob/sycl/buildbot/configure.py) script are the ones commonly used by DPC++ developers and might not necessarily suffice for your project-specific needs.

Not all of our users use `configure.py` script and we mostly use this script for daily development and CI.

**Comment by dvrogozh** [comment]
@uditagarwal97, with all respect, but what you suggest and highlight does not make sense to me. Per my opinion the proposal you are making is an attempt to workaround initially wrong implementation done in the SYCL library CMake file motivated by highly controversial idea of convenience to use static library and in direct contradiction with the established practice in the upstream LLVM. I strongly recommend to reconsider your recommendation and align behavior with the upstream LLVM practice. Note that right now is a very good time to do so considering that v7.0.0 is a next major release series of DPC++ compiler which is not yet released, so changes in the default behavior if any are totally expected at this very moment. I still don't see however which changes in "default" behavior you are talking about considering that LLVM+cmake already have everything needed to tune the build, i.e. `BUILD_SHARED_LIBS`, `LLVM_ENABLE_ZSTD` and `LLVM_USE_STATIC_ZSTD`.

I would also like to point out that even following your idea we will need to patch not only SYCL cmake, but also LLVM and LLD cmakes as well. Please, review the respective code pieces I've pointed to in the PR description.

I am absolutely not ok to follow your recommendation to change the PR I have proposed. That is a wrong thing to do per my opinion. This would complicate the code and diverge from the established practice to handle zstd library in upstream LLVM. If you chose not to accept the contribution proposed in this PR, I do expect that you provide the resolution for the following issue which is one of the issues blocking CI enabling on pytorch side for intel/llvm compiler path:
* https://github.com/intel/llvm/issues/22310

**Comment by uditagarwal97** [comment]
> @uditagarwal97, with all respect, but what you suggest and highlight does not make sense to me. Per my opinion the proposal you are making is an attempt to workaround initially wrong implementation done in the SYCL library CMake file motivated by highly controversial idea of convenience to use static library and in direct contradiction with the established practice in the upstream LLVM. I strongly recommend to reconsider your recommendation and align behavior with the upstream LLVM practice. 

I'm not sure what was not clear in my previous comment and I would disagree about the initial implementation being incorrect. Upstream LLVM has an optional runtime dependency on `zstd`, we don't want that in DPCPP. We don't want our users to have zstd installed on their system just to use Intel compiler. And for what it is worth, I'd like to highlight that install zstd on Windows and older RHEL OS is not trivial. User would have to build/download package and add to environment manually. The divergence from upstream LLVM is done solely for the convenience of our users 😄 

>Note that right now is a very good time to do so considering that v7.0.0 is a next major release series of DPC++ compiler which is not yet released, so changes in the default behavior if any are totally expected at this very moment. I still don't see however which changes in "default" behavior you are talking about considering that LLVM+cmake already have everything needed to tune the build, i.e. BUILD_SHARED_LIBS, LLVM_ENABLE_ZSTD and LLVM_USE_STATIC_ZSTD.

Quote from my previous comment about current DPCPP build behavior:

> Even if the user doesn't set LLVM_USE_STATIC_ZSTD, the current DPCPP build always links zstd static library. But, after your PR, that behavior will change and now it will start linking against shared zstd library, if it is available.

All I want is for this behavior to stay the same. You can achieve that by setting `LLVM_USE_STATIC_ZSTD` in `sycl/CMakeList` if user hasn't already set this flag. This way, for Fedora and other OS on which you want DPCPP to build with shared zstd, you can just pass `LLVM_USE_STATIC_ZSTD=0` flag. All other users will stay unaffected.

> I would also like to point out that even following your idea we will need to patch not only SYCL cmake, but also LLVM and LLD cmakes as well. Please, review the respective code pieces I've pointed to in the PR description.

Sorry, how? Why would we need to change LLVM/LLD Cmake files? On Fedora, if we build DPCPP with `LLVM_USE_STATIC_ZSTD=0` flag, LLVM, LLD, SYCL, will all use dynamic zstd.

> I am absolutely not ok to follow your recommendation to change the PR I have proposed. That is a wrong thing to do per my opinion. This would complicate the code and diverge from the established practice to handle zstd library in upstream LLVM. 

I am not the sole maintainer/reviewer in intel/llvm, so if anyone else feel comfortable with the change in this PR, they can approve it. I'd have no objections to it. Personally, based on my prior experience enabling zstd in intel/llvm, I think this change will bring unnecessary inconvenience to our users, and so I'm not comfortable approving it myself.

> If you chose not to accept the contribution proposed in this PR, I do expect that you provide the resolution for the following issue which is one of the issues blocking CI enabling on pytorch side for intel/llvm compiler path:

It's simple. Quote from my prior comment:
```
#ifndef LLVM_USE_STATIC_ZSTD
#define LLVM_USE_STATIC_ZSTD 1
#endif

#if LLVM_USE_STATIC_ZSTD 
// Use static zstd
#else
// Use shared
#endif
```
Can we have something like this in `sycl/CMakeList`? For Fedora and other distros where you want to link against shared `zstd` library, you can just pass `LLVM_USE_STATIC_ZSTD=0`

**Comment by dvrogozh** [comment]
> I'd like to highlight that install zstd on Windows and older RHEL OS is not trivial. User would have to build/download package and add to environment manually. The divergence from upstream LLVM is done solely for the convenience of our users.

What you describe is a standard situation in Linux ecosystem development when some new dependency is being introduced and adopted. Instead of swimming against the current and introduce non-standard development approaches it's much better to recognize that 1) there are already know ways to handle what you want to handle, 2) they exist for the reason, 3) they were introduced as a result of the actual experience many Linux developers in the community. I understand that on Windows it's a pain to build almost anything, but that's nether an excuse to step out from open source community practices. If you will look deeper you will find out that these practices do cover Windows case as well.

**Comment by uditagarwal97** [comment]
> > I'd like to highlight that install zstd on Windows and older RHEL OS is not trivial. User would have to build/download package and add to environment manually. The divergence from upstream LLVM is done solely for the convenience of our users.
> 
> What you describe is a standard situation in Linux ecosystem development when some new dependency is being introduced and adopted. Instead of swimming against the current and introduce non-standard development approaches it's much better to recognize that 1) there are already know ways to handle what you want to handle, 2) they exist for the reason, 3) they were introduced as a result of the actual experience many Linux developers in the community. I understand that on Windows it's a pain to build almost anything, but that's nether an excuse to step out from open source community practices. If you will look deeper you will find out that these practices do cover Windows case as well.

I understand your concern and if you feel strongly about making zstd a runtime dependency of DPCPP, let's start an internal discussion including SYCL architects and DPCPP component owners. But, we should definitely have a thorough discussion first before introducing a new runtime dependency to DPCPP. For the time being, to unblock Pytorch, can we use the workaround that I suggested?  I am open to discussing other approaches as well.

**Comment by dvrogozh** [comment]
> if you feel strongly about making zstd a runtime dependency of DPCPP, let's start an internal discussion including SYCL architects and DPCPP component owners.

I don't feel that this needs to be discussed. This sounds like bureaucracy discussion for no reason.

This is a strong requirement from Linux distros to support a build and runtime of the component (intel/llvm) against system installed dependencies. Note that a word "support" is important here - it means that this can be exposed as a choice to the user who will decide if he wants to have a runtime dependency or will prefer to link it in statically. The existing LLVM options already cover all these cases. In other words - this is not actually a component (DPCPP) call to use zstd as a static library, that's a user call. Note that if left unfixed this will be overridden by the patch carried on the Linux distro side.

**Comment by uditagarwal97** [comment]
> > if you feel strongly about making zstd a runtime dependency of DPCPP, let's start an internal discussion including SYCL architects and DPCPP component owners.
> 
> I don't feel that this needs to be discussed. This sounds like bureaucracy discussion for no reason.
> 

I'm sorry if you feel that it's a bureaucratic discussion. Let me reiterate that it's done this way solely for the convenience of our users. If you have any alternative approach/ideas which solves your use case without being inconvenient to other users, I'm all ears.

**Comment by sarnex** [comment]
I tried my best to follow the discussion so far. I definitely agree that silently requiring a new runtime dependency for DPCPP is not ideal and definitely would require discussion. 

I originally wrote a huge summary of my investigation, but the TLDR is this:

I think the only case to worry about is when the user isn't using `configure.py`, and they are NOT passing anything for `LLVM_USE_STATIC_ZSTD`. 

Note `LLVM_USE_STATIC_ZSTD` is default `OFF` in LLVM CMake code.

`configure.py` will still pass `LLVM_USE_STATIC_ZSTD=ON` with this change, and if the user is not using `configure.py` and passes something to CMake directly for `LLVM_USE_STATIC_ZSTD`, they know what they're doing.

I was originally concerned that there was some case where we would introduce a silent runtime dependency on `libzstd.so` without the user explicitly passing a related option.

Actually, that will happen for `libsycl.so`.

However the key point is `libsycl.so` links against `LLVMSupport`, which has the [standard](https://github.com/intel/llvm/blob/sycl/llvm/lib/Support/CMakeLists.txt#L29) LLVM ZSTD logic that, if `LLVM_USE_STATIC_ZSTD` is not `ON`, uses `libzstd.so` (shared library) by default if found and disables ZSTD support otherwise. 

So `LLVMSupport` will find and use `libzstd.so` if `LLVM_USE_STATIC_ZSTD` is not `ON`.

If `libzstd.so` isn't found, it sets `LLVM_ENABLE_ZSTD` to false, so even SYCL will disable ZSTD support and not try to use `libzstd.a`.

Actually if we do a build today just taking `configure.py --print-cmake-flags` results and remove `-DLLVM_USE_STATIC_ZSTD=ON`, we indeed see `libsycl.so` already depends on `libzstd.so` at runtime:

```
root@8ef0c8762759:/tmp/llvm/build# ldd lib/libsycl.so
	linux-vdso.so.1 (0x00007ffe05a7a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff79be03000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007ff79bd49000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff79bacb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff79b9e2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff79b7d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff79ccbc000)

```

and the dep is brought in from `LLVMSupport`.

I did a shared library build separately to confirm `LLVMSupport` links against `libzstd.so` in this case and `libsycl` links against `libzstd.a`.

Given that there should be no new hidden runtime dependency, are you okay with this change @uditagarwal97?

Also @dvrogozh, there is a compile error on Windows from this PR:

```
D:\github\_work\llvm\llvm\src\sycl\source\detail/compression.hpp(16): fatal error C1083: Cannot open include file: 'zstd.h': No such file or directory
```
Probably it's because you removed the `target_include_directories` call and we are not using the native CMake target. Please either add back `target_include_directories` (with the right new variable name) or port this code to use the CMake target so we only need to link.

**Comment by uditagarwal97** [comment]
> LLVMSupport

@sarnex SYCL library does not link against `LLVMSupport` always. Steffen tried to do so (see https://github.com/intel/llvm/pull/18572) but had to revert back due to some other issues.

Looking at SYCL CMake files, we link with `LLVMSupport` only for a specific case: https://github.com/intel/llvm/blob/ecfb4604ccce95afffafa8d85ebf3b208376da8d/sycl/source/CMakeLists.txt#L125
when `SYCL_ENABLE_STACK_PRINTING` is enabled.

**Comment by sarnex** [comment]
It looks like that's off by default, I had it off locally too and we were still linking against `LLVMSupport`/`libzstd.so`, I could try to track it down but I'm not sure it's worth it.

But you're right, there might be some case where we still start linking against `libzstd.so`, even though I can't reproduce it.

However, I feel this is acceptable because:
1) Using libraries when found on the user's system is standard practice, opt-in is pretty rare.
2) I'm pretty sure we don't claim support for a portable compiler, where you are expected to be able to take the compiler binaries onto a different system with different libraries installed
3) This change would be going into a major release, so while I don't think this is considered ABI-breaking, it would be in an ABI-breaking release
4) The current implementation differs from upstream LLVM in a way that many would perceive as a bug
5) The situation where a user would see the dependency introduced is pretty unlikely, I can't even reproduce it myself.

**Comment by uditagarwal97** [comment]
> It looks like that's off by default, I had it off locally too and we were still linking against `LLVMSupport`/`libzstd.so`, I could try to track it down but I'm not sure it's worth it.
> 
> But you're right, there might be some case where we still start linking against `libzstd.so`, even though I can't reproduce it.
> 
> However, I feel this is acceptable because:
> 
> 1. Using libraries when found on the user's system is standard practice, opt-in is pretty rare.
> 2. I'm pretty sure we don't claim support for a portable compiler, where you are expected to be able to take the compiler binaries onto a different system with different libraries installed

Isn't that what a majority of intel/llvm customer's do? For example, before we started publishing open-source releases, Blender used to take intel/llvm sources, compile SYCL, and distribute SYCL RT and other libraries along with Blender libraries. I think it is a common workflow among our users, and this change will end up introducing a silent runtime dependency to SYCL RT. 

> 3. This change would be going into a major release, so while I don't think this is considered ABI-breaking, it would be in an ABI-breaking release

It's unrelated to ABI.

> 4. The current implementation differs from upstream LLVM in a way that many would perceive as a bug

The argument that something is a "standard practice" or "aligning to upstream LLVM" is pretty weak IMO - different projects have different requirements, different users, and different accountability towards users, we shouldn't forcefully align to the upstream at the expense of our users.

> 5. The situation where a user would see the dependency introduced is pretty unlikely, I can't even reproduce it myself.

That's exactly the problem I'm referring to - silently making zstd a runtime dependency of SYCL RT. Try building SYCL RT with shared zstd and use it on a system without zstd installed.

I'm not against making zstd a runtime dependency of SYCL RT but it has to a conscious decision, discussed with relevant stakeholders. Two years ago when I had this discussion with SYCL Architects, we ended up deciding to opt for static zstd linking by default for the same reasons I mentioned previously.
I personally don't find the motivation behind this change strong enough to justify whatever trouble it will cause, given that there's a very simple fix available (see my previous comments).

Edit:- These are just my personal opinions. If someone else is willing to take accountability of this change, please feel free to approve and merge, I won't have any objections to it.

**Comment by dvrogozh** [comment]
> Also @dvrogozh, there is a compile error on Windows from this PR:
> Probably it's because you removed the `target_include_directories` call and we are not using the native CMake target.

That's because I removed `target_include_directories`, but not because zstd is not a target. It's an imported target with the set include paths:
https://github.com/intel/llvm/blob/6e4dcd88fc5a6aea0faac662b62c716bdb044e15/llvm/cmake/modules/Findzstd.cmake#L94-L97

The problem was that I have overlooked that there are 2 sycl targets being setup here: `${LIB_NAME}` and `${LIB_OBJ_NAME}`. By removing `target_include_directories` I accidentally dropped dependency on zstd for `${LIB_OBJ_NAME}`. I returned `target_include_directories` in the last update.

**Comment by sarnex** [comment]
@dvrogozh How do you intend to handle this in Pytorch CI? 
Is Pytorch going to also ship `libzstd.so` in addition to the SYCL compiler binaries?

**Comment by dvrogozh** [comment]
> @dvrogozh How do you intend to handle this in Pytorch CI? Is Pytorch going to also ship libzstd.so in addition to the SYCL compiler binaries?

That's a decision for those who create a package. But talking about the Pytorch CI working with intel/llvm compiler, the setup which we already implemented is reliance on the Linux native package managers to handle the dependency. I.e. the user will need to `apt-get install libzstd` if he self-builds intel/llvm or the `libzstd` will get installed as a configured dependency if intel/llvm is installed in a package form.

Note that for the Pytorch CI the only thing which I needed to do is to explicitly install `libzstd-dev` on almalinux 8 to be able to self-build inte/llvm (which is a normal development process on Linux). Rruntime ZSTD library is already included by default into even minimal docker images of at least almalinux and ubuntu families:
```
dvrogozh@DUT7308PVC:~$ docker run -it --rm almalinux:8
[root@108c8584ebd9 /]# find / -name libzstd*
/usr/lib64/libzstd.so.1.4.4
/usr/lib64/libzstd.so.1
[root@108c8584ebd9 /]# exit

dvrogozh@DUT7308PVC:~$ docker run -it --rm ubuntu:22.04
root@4996ad3e05a6:/# find / -name libzstd*
/usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
/usr/lib/x86_64-linux-gnu/libzstd.so.1
```

**Comment by sarnex** [comment]
> That's a decision for those who create a package. But talking about the Pytorch CI working with intel/llvm compiler, the setup which we already implemented is reliance on the Linux native package managers to handle the dependency. I.e. the user will need to apt-get install libzstd if he self-builds intel/llvm or the libzstd will get installed as a configured dependency if intel/llvm is installed in a package form.

Does that behavior match how other Pytorch dependencies are handled? I'm asking because I haven't built Pytorch but I have built Blender which packages all dependencies into a huge archive that should be downloaded before running compile and the package manager is not needed.

**Comment by dvrogozh** [comment]
This depends on who packages Pytorch, how and for which purpose. Upstream pytorch production wheels target multiple Linux distributions at once, so they indeed are doing big archives with key dependencies, not all, but those which prevent basic pytorch usage such as `import pytorch`. Other dependencies (such as, for example, drivers) are not packaged. Also, CI builds might use different patterns stepping out from the archived dependencies. Downstream pytorch packages coming from Linux distros would rely on Linux package managers to bring in all the dependencies as distro packages suites the role of the archives you are talking about. Other parties might use one way or another depending on the needs.

Overall, that's important to give users flexibility instead of hardcoding one solution or another. Option must be available to configure both paths. Per my understanding what upstream LLVM provides already satisfies this need.

**Comment by sarnex** [comment]
Right, I guess what I am trying to ask is, if we go with this approach, is any work required in Pytorch to ensure SYCL compiler dependencies (eg. `libzstd`) are handled the same as other compiler (CUDA/HIP) dependencies, or is the current SYCL compiler setup in Pytorch already what we want?

**Comment by dvrogozh** [comment]
>Is the current SYCL compiler setup in Pytorch already what we want?

Well, it's not what we want because Pytorch is using closed source DPC++ compiler while we want it to use open source DPC++ one (intel/llvm). That being said, interpolating from closed source DPC++ to open source DPC++ one, what currently closed source DPC++ has is fine for Pytorch production builds. As for the intel/llvm we are forced to setup parallel and different workflow at the moment which sometimes allows to step out from the existing patterns we had for closed source DPC++ compiler. That's not bad by the way as it allows to find issues which will be blocking for other setups, such as packaging Pytorch into Linux distros (and our ZSTD issue is such an issue).

If you ask if you need to change anything in intel/llvm CI to package libzstd dependency or link it in as stack, then that is not necessary.

By the way, I searched regarding zstd in modern distros. It seems it's getting included into the base images nowadays because package managers (apt, rpm, dnf, etc.) depend on it. That being said ultra-light images might now include it (such as `alpine`) as they often come with dedicated package managers.

**Comment by sarnex** [comment]
Differing from the closed-source compiler is fine with me, I'm concerned about other open-source dependencies in Pytorch.

This change is fine with me if we restrict it to Linux. Windows is very different, and while it may differ from upstream, I think we have a real risk of breaking customers there, while the risk seems very low on Linux.

**Comment by dvrogozh** [comment]
>  Windows is very different, and while it may differ from upstream, I think we have a real risk of breaking customers there, while the risk seems very low on Linux.

@sarnex , I've limited the change to Linux. Please, check if you are ok with the conditioning or want to merge Windows and Linux static branch together.

**Comment by sarnex** [comment]
Thanks, I will take a look tomorrow

**Review by sarnex — APPROVED** [review]
I'm okay with this change for the following reasons:

1) It is restricted to Linux, so Windows will always use the static library
2) I plan to revert the change in its entirety for the internal compiler, where we have a large user base on exotic Linux installs
3) It seems pretty much every Linux distro going back many versions has `libzstd.so` pre-installed, so users are unlikely to hit an issue
4) We want to improve packaging for Linux distros, who are in general against static library usage
5) In my testing we already depend on `libzstd.so` on Linux if the build system has it, however it seems the nighties we provide do not.
6) There is no behavior change in the produced binaries (nightly or otherwise) with this change as `configure.py` still specifies usage of static zstd

**Comment by sarnex** [comment]
@uditagarwal97 I understand you may not approve this change, but please let me know if you want to block my merging of it.

**Comment by uditagarwal97** [comment]
> @uditagarwal97 I understand you may not approve this change, but please let me know if you want to block my merging of it.

Nope. I'm fine with merging it.

**Comment by sarnex** [comment]
Thanks, and thanks for the discussion
