### ISSUE TITLE
[SYCL] lazy expression evaluation CRTP zeros on gpu, works on cpu

### ISSUE THREAD

**Issue by bd4** [intel/llvm#1687]
I am porting [gtensor](https://github.com/wdmapp/gtensor) to SYCL. It uses CRTP expression classes to support lazy expression building of kernels to run on the GPU. When run with `SYCL_DEVICE_TYPE=gpu`, the build succeeds but results are mysteriously being set to 0 everywhere. It works fine for `SYCL_DEVICE_TYPE=cpu`. I created a small reproducer - the simple expressions work even on GPU, and the complex/recursive expression is resulting in 0s on GPU.

I am using beta06, with intel-compute-runtime build from git at 20.15.16524.r46.gbd24350a6-1.

```
#include <iostream>
#include <CL/sycl.hpp>

template <typename T>
struct plus {
  auto operator()(T left, T right) -> T {
    return left + right;
  }
};

template <typename T>
struct times {
  auto operator()(T left, T right) -> T {
    return left * right;
  }
};

template <typename DerivedExpression>
class expression {
protected:
  expression() = default;

public:
  using derived_type = DerivedExpression;

  const derived_type& derived() const&;
  derived_type& derived() &;
  derived_type derived() &&;
};

template <typename DerivedExpression>
inline auto expression<DerivedExpression>::derived() const&
-> const derived_type& {
    return static_cast<const derived_type&>(*this);
}

template <typename DerivedExpression>
inline auto expression<DerivedExpression>::derived() & -> derived_type& {
    return static_cast<derived_type&>(*this);
}

template <typename DerivedExpression>
inline auto expression<DerivedExpression>::derived() && -> derived_type {
    return static_cast<derived_type&&>(*this);
}

template <typename Result, typename Arg>
class constfn {
    public:
      using result_type = Result;
      using arg_type = Arg;

      constfn(result_type v) : v_(v) {}

      result_type operator() (arg_type arg) {
          return v_;
      }

    private:
      result_type v_;
};

template <typename Result, typename Arg>
class linearfn {
    public:
      using result_type = Result;
      using arg_type = Arg;

      linearfn(result_type m, result_type b) : m_(m), b_(b) {}

      result_type operator() (arg_type arg) {
          return m_ * arg + b_;
      }

    private:
      result_type m_;
      result_type b_;
};

template <typename F, typename T>
class binaryclosure {
  public:
    binaryclosure(F&& f, T&& arg0, T&& arg1)
    : f_(std::forward<F>(f)),
      arg0_(std::forward<T>(arg0)),
      arg1_(std::forward<T>(arg1))
    {}

    T operator() () {
      return f_(arg0_, arg1_);
    }

  private:
    F f_;
    T arg0_;
    T arg1_;
};

template <typename F, typename E1, typename E2>
class binaryexpr;

template <typename F, typename E1, typename E2>
class binaryexpr : public expression<binaryexpr<F, E1, E2>> {
  public:
    using self_type = binaryexpr<F, E1, E2>;
    using base_type = expression<self_type>;
    using function_type = F;
    using expression_type_1 = E1;
    using expression_type_2 = E2;

    binaryexpr(F&& f, E1&& e1, E2&& e2)
    : f_(std::forward<F>(f)),
      e1_(std::forward<E1>(e1)),
      e2_(std::forward<E2>(e2))
    {}

    template <typename Arg>
    auto operator() (Arg arg);

  private:
    F f_;
    E1 e1_;
    E2 e2_;
};

template <typename F, typename E1, typename E2>
template <typename Arg>
auto binaryexpr<F, E1, E2>::operator()(Arg arg) {
    return f_(e1_(arg), e2_(arg));
}

template <typename F, typename E1, typename E2>
auto mkexpr(F&& f, E1&& e1, E2&& e2)
{
  return binaryexpr<F, E1, E2>(std::forward<F>(f),
                               std::forward<E1>(e1),
                               std::forward<E2>(e2));
}

int main(int argc, char **argv) {
    constexpr std::size_t N = 16;
    std::vector<double> h_x(N);
    std::vector<double> h_y(N);
    std::vector<double> h_z(N);

    for (int i=0; i<N; i++) {
        h_x[i] = static_cast<double>(i);
    }

    auto q = sycl::queue{};
    auto dev = q.get_device();
    std::string type;
    if (dev.is_cpu()) {
        type = "CPU  ";
    } else if (dev.is_gpu()) {
        type = "GPU  ";
    } else if (dev.is_host()) {
        type = "HOST ";
    } else {
        type = "OTHER";
    }
    std::cout << "[" << type << "] "
              << dev.get_info<sycl::info::device::name>()
              << " {" << dev.get_info<sycl::info::device::vendor>() << "}"
              << std::endl;

    auto k_fun = binaryclosure<plus<double>, double>(plus<double>{}, 7, 11);

    using dconst = constfn<double, double>;
    using dlinear = linearfn<double, double>;
    auto k_expr_const = mkexpr(plus<double>{}, dconst{2.0}, dconst{7.5});
    auto k_expr_linear = mkexpr(plus<double>{}, dlinear{2.0, 1.0},
                                dlinear{0.0, 7.5});
    auto k_expr_complex = mkexpr(plus<double>{}, k_expr_const, k_expr_linear);

    // 4x^2
    auto k_expr_mult = mkexpr(times<double>{}, dlinear{2.0, 0.0},
                              dlinear{2.0, 0.0});
    {
        sycl::buffer<double, 1> buf_x{h_x.data(), sycl::range<1>{N}};
        sycl::buffer<double, 1> buf_y{h_y.data(), sycl::range<1>{N}};
        sycl::buffer<double, 1> buf_z{h_z.data(), sycl::range<1>{N}};

        auto e = q.submit([&](sycl::handler &cgh) {
          auto acc_x = buf_x.get_access<sycl::access::mode::write>(cgh);
          auto acc_y = buf_y.get_access<sycl::access::mode::write>(cgh);
          auto acc_z = buf_z.get_access<sycl::access::mode::write>(cgh);
          cgh.parallel_for(sycl::range<1>(N),
          [=](sycl::item<1> item) mutable {
             int i = item.get_linear_id();
             acc_x[i] = k_expr_const(i);
             acc_y[i] = k_expr_linear(i);
             acc_z[i] = k_expr_complex(i);
          });
        });
    }

    for (int i=0; i<N; i++) {
        std::cout << h_x[i] << " + " << h_y[i] << " = " << h_z[i] << std::endl;
    }
}
```

**Comment by bd4** [comment]
Interestingly hipSYCL 0.8.1-20200501 running on ROCm on a different machine results in the same zero-ing of the complex expression with the above test program. Is there something in the spec which precludes this from working, or just happens to be a common bug?

**Comment by bd4** [comment]
Trying to compile the reproducer using ComputCpp CE 1.3.0, with spirv64 target and intel-computer-runtime, and I get the following error:

```
expr.cxx:79:25: error: [Computecpp:CC0011]: cannot capture object k_expr_complex
      of type 'class binaryexpr<struct plus<double>, class binaryexpr<struct
      plus<double>, class constfn<double, double>, class constfn<double, double>
      > &, class binaryexpr<struct plus<double>, class linearfn<double, double>,
      class linearfn<double, double> > &>' in a SYCL kernel, because it is a non
      standard-layout type
             acc_z[i] = k_expr_complex(i);
                        ^
expr.cxx:60:5: note: captured object defined here
    auto k_expr_complex = mkexpr(plus<double>{}, k_expr_const, k_expr_linear);
    ^
In file included from expr.cxx:23:
./expr.hpp:135:5: error: [Computecpp:CC0023]: class binaryexpr is not standard
      layout, because it contains a non-static field with reference type
    E1 e1_;
```
Need to wrap my head around why LLVM wants to deduce the sub-expressions as references. Perhaps a failed capture of the sub-expressions explains the failures in hipSYCL and dpcpp as well... if so a compile error is definitely warranted.

**Comment by bd4** [comment]
Ok, if I use `std::move` in the definition it removes the deduced references and works in DPCPP and ComputeCpp CE 1.3.0:
```
-    auto k_expr_complex = mkexpr(plus<double>{}, k_expr_const, k_expr_linear);
+    auto k_expr_complex = mkexpr(plus<double>{}, std::move(k_expr_const),
+                                 std::move(k_expr_linear));
```
I think this is still a bug in the sense that the compiler should produce an error rather than silently producing bogus results, i.e. the computecpp behavior is better.

**Comment by keryell** [comment]
SYCL 1.2.1 supports only standard-layout & trivially copyable data types. Next version will require only trivially copyable data types. Perhaps DPC++ support this already?
Furthermore mutable lambda as kernel are not supported. But you can have another mutable lambda in your kernel...

**Comment by bd4** [comment]
Thanks @keryell . I have an updated version of my example at https://github.com/bd4/dpcpp-test/blob/master/expr.cxx which is compiling and running correctly with all three platforms, with non-mutable kernel and forcing the expressions types to be inferred without references so they have standard layout.

It seems that many implementations don't enforce the non-mutable kernel lambda requirement. It comes up in gtensor when using a gtensor object on the LHS, I will look into how to work around this. My WIP gtensor port also uses USM, currently usm_allocator with std::vector, as the storage for the multi-d arrays. It may be simpler in some ways to use `sycl::device_malloc` instead, to reduce the number of layers involved.

**Comment by keryell** [comment]
> It seems that many implementations don't enforce the non-mutable kernel lambda requirement

Because we discovered the fundamental problem only recently... This requirement is expected in the next SYCL version.

**Comment by keryell** [comment]
Otherwise I a little bit worried about your `static_cast<const derived_type&>(*this)` on device... If the goal is to do an equivalent of a virtual table, it might not work since the typical OpenCL 1.2-like hardware does not support using function pointers.

**Comment by bd4** [comment]
Re the derived type cast, Codeplay has a blog post about using it as an alternative to dynamic polymorphism:
https://www.codeplay.com/portal/07-12-19-enabling-polymorphism-in-sycl-using-the-cpp-idiom-crtp
It should all be resolved at compile time with no function pointers involved.

I am still cleaning things up, but so far changing the `gfunction` type in gtensor to use two members for sub-expressions instead of a std::tuple (not standard layout or trivially copyable) has fixed all the issues with my simple test case, so the CRTP and the accompanying static casts seem to work fine.

Can you point me at some discussion of the mutable lambda issue? I am trying to wrap my head around this. sycl accessors clearly allow data modification, and gtensor can too by allowing modification on a const gtensor, but I want to make sure I understand the nuances here.

**Comment by keryell** [comment]
My question for the `static_cast<const derived_type&>(*this)` is whether in your example you have the same value uniformly across the work-items or not.
Of course if it is uniform and resolved ouside of the kernel it is good. Otherwise I am unsure it will work on all hardware.

The problem for `mutable` lambda is not because of the accessors (because it is design to work with accessors and non-mutable lambdas) but more like what to do with a kernel such as
```c++
[=, auto i = 42] (auto idx) mutable {
  a[idx] = ++i;
}
```
What is the value of i across work-items? It looks shared across work-items...
What happens if the run time copy the kernels?

**Comment by paboyle** [comment]
I'm interested to implement a view object copied to device, but which maintains reference counts on host. 
What's the long term plan for lambda capture?
Is there a way to have a non-trivial constructor/destructor on host, but SYCL_DEVICE_ONLY it on device?

**Comment by bd4** [comment]
@keryell thanks for the mutable lambda example, I can see how that would cause problems. 

The `gtensor` objects are always uniform, they are basically just wrappers around device (or host) memory that resolve multi-dimensional indexing. And the expressions / views built on top of them are also element wise uniform. All the resolution should happen at compile time, so on device each work-item is doing an index calculation, then accessing memory and evaluating any expression at that index.

I think the natural solution to avoid mutable lambda's in gtensor is to have the operator() of a const `gtensor_device` array return a non-const ref to the element. I assume the buffer objects are doing something similar?

I have also been looking at the ComputeCpp experimental USM implementation. It requires a usm_wrapper<T> object around the USM pointers before they are captured by a lambda (see https://github.com/codeplaysoftware/syclacademy/tree/master/Code_Exercises/Exercise_7_Unified_Shared_Memory_Ext). I'm wondering if this is a proposed modification before including in the SYCL standard? The wrapper seems rather awkward for gtensor, since the USM pointers are nested inside a CRTP expression hierarchy, and the non-wrapped version still needs to be used for the memcpy operations.

@paboyle I'm not sure how much help this will be, but you can take a look at the gtensor port (still WIP but already running on oneapi beta6): https://github.com/wdmapp/gtensor/pull/19. The data structures don't strictly meet the requirements for SYCL 1.2.1, but dpcpp does not enforce them. I think there is a disparity between the definitions for 'trivially copyable' and 'standard layout' and what can truly be byte-wise mem copied for capture into a lambda / passed to device code, i.e. the definitions are unnecessarily strict (and in fact it the standard layout requirement may be dropped in the next SYCL standard). I don't understand the nuances yet, but I think there is some legacy OpenCL stuff involved. In practice the one issue I ran into was with std::tuple, which does not behave nicely in SYCL device code. Can you say more about your use case / link to WIP code?

**Comment by paboyle** [comment]
Interesting Bryce - your .to_kernel   is very similar to my use of   
auto view = Lattice<T>.View(mode);

In for example:

https://github.com/paboyle/Grid/blob/sycl/Grid/lattice/Lattice_view.h

I'm hacking it around a bit, but trying to make a sequence like

```
template<class obj1,class obj2,class obj3> inline
void add(Lattice<obj1> &ret,const Lattice<obj2> &lhs,const Lattice<obj3> &rhs){
  auto ret_v = ret.View(AcceleratorWrite);
  auto lhs_v = lhs.View(AcceleratorRead);
  auto rhs_v = rhs.View(AcceleratorRead);
  accelerator_for(ss,lhs_v.size(),obj1::Nsimd(),{
    decltype(coalescedRead(obj1())) tmp;
    auto lhs_t=lhs_v(ss);
    auto rhs_t=rhs_v(ss);
    add(&tmp,&lhs_t,&rhs_t);
    coalescedWrite(ret_v[ss],tmp);
  });
}
```

This trigger actions when the "views" are deleted. My code has so far assumed UVM / SVM
but want to use this to drive a software cache (under my control) on the device.

So when one of these temporary View objects is created it triggers a possible cache fill action, and when deleted it informs the cache the view is gone. I might want to copy these things around though, and wanted to use a smart pointer of ref counter of some form Thing is I don't want that to interact with the lambda.

I had reached the conclusion I'm going to be forced to an open/close semantic on this things and not drive it from construct and delete due to SYCL constraints.

What are your to_kernel() calls creating ?

**Comment by bd4** [comment]
> What are your to_kernel() calls creating ?
The return depends on the type of the expression, but the basic idea is to convert the expression to only device pointers and trivially copyable data. CUDA was the initial target, so this basically boiled down to what you can pass as a parameter to a kernel. For simple gtensor's, which is the main multi-dimensional array container, it returns a `gtensor_view`. This is basically a multi-dimensional span - pointer to device data, shape of the array, strides for the array. Both shape and strides are templated fixed sized arrays according to the dimensionality, so they can be easily copied. For SYCL USM relaxes the restriction on passing pointers in 1.2.1 spec and allows device pointers to be passed.

**Comment by bd4** [comment]
@paboyle Is what you are trying to do analogous to SYCL buffers and accessors? The buffer is constructed on the host and it's lifetime can be used to trigger copy back, but it can't be used directly on the device. For that an accessor is needed. The buffer is often constructed from an existing data structure, like std::vector, and it internally manages buffering to/from device. Getting an accessor for a buffer requires passing a CommandGroupHandler, which can control scheduling and perhaps ref counting?

**Comment by paboyle** [comment]
Hi Bryce,
yes bears some analogies - I'd ideally trigger the data motion from object activity, implicit under rules & containers of my own creation. But

1) I'm trying to not tie myself to SYCL, but use the availability of pointers to do this cross platform on HIP, SyCL and CUDA.

2) Not tie myself to SyCL's scoping rules - for these accessors.

In particular, I'm developing my own software caching rules including a transient/non temporal hint so the certain vectors can be marked as "evict next". 

I can do this in ET's quiet easily, but for general accelerator_for code, I'd ideally be able to set up a "View" object (analogous to accessor) but be able to control what it does on object copy and deletion on host and device separately. Basically when the last host copy dies, I need to unlock the cache

This can be avoided if I insist the caller do a manual "open" / "close" pair, but its would be better to make a ref counted object which triggers close action on last (host) copy deletion.

**Comment by paboyle** [comment]
I figured out an O(1) caching table scheme using combo of "unordered_map<addr,Entry>" and list<addr> for maintaining true LRU with multiple priorities for eviction and locking of open views.
It's under implementation... but should work. Have proof of concept done.

My remaining question is how much syntactical sugar do I need to leave the code using it as pretty as my original SVM/UVM code.

**Comment by bd4** [comment]
Re `std::tuple` that was the original cause of the problem in gtensor, codeplay has an Apache-2 licensed tuple implementation that is SYCL friendly: https://github.com/codeplaysoftware/computecpp-sdk/blob/master/include/stl-tuple/STLTuple.hpp. Useful if we want to add n-ary operators to gtensor, so far it is just unary / binary so wasn't a big deal to template out two different classes.

@paboyle Codeplay's visioncpp library might be a useful source of ideas for your Grid port: https://github.com/codeplaysoftware/visioncpp. They also have an expression language for GPU code, using buffer/accessor model without USM. There is also this as an interesting virtual pointer example (works in all SYCL implementations): https://github.com/codeplaysoftware/computecpp-sdk/blob/master/samples/vptr.cpp.

**Comment by bd4** [comment]
Closing, this is working for us on latest oneAPI. More importantly, the SYCL backend of gtensor (https://github.com/wdmapp/gtensor/), much more complex the the CRTP example linked above, is also working. Some refactoring was required to make everything work with non-mutable lambdas.
