### ISSUE TITLE
[SYCL][unittests] Several unittests postcommit failures after 9992f2a

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#13592]
### Describe the bug

Fist post commit failure: https://github.com/intel/llvm/actions/runs/8853888908/job/24315708190#step:12:1513 appeared after https://github.com/intel/llvm/pull/13569 got merged.

```
/__w/llvm/llvm/src/sycl/include/CL/sycl.hpp:12:2: error: #warning is a C++23 extension [-Werror,-Wpedantic]
   12 | #warning "CL/sycl.hpp is deprecated, use sycl/sycl.hpp"
      |  ^
/__w/llvm/llvm/src/sycl/include/CL/sycl.hpp:12:2: error: "CL/sycl.hpp is deprecated, use sycl/sycl.hpp" [-Werror,-W#warnings]
```

### To reproduce

DPC++ commit: [9992f2a](https://github.com/intel/llvm/commit/9992f2ae41da3b19e3436337c9cc3fcc95e66e98)

**Comment by uditagarwal97** [comment]
@aelovikov-intel FYI. It is weird that we see these failures only in post-commit but not in pre-commit (https://github.com/intel/llvm/pull/13569). I wonder if there's some differences in check-sycl-unittests configuration in pre and post commit.
