### PR TITLE
[SYCL][Test] Make get_invalid_kernel_id.cpp linker-agnostic

### PR DESCRIPTION
**Pull request by wenju-he**
CHECK-LINUX previously matched only ld.bfd's "undefined reference to" wording. Under parallel test execution, clang can select lld instead, which emits "undefined symbol:" with different punctuation, causing spurious FileCheck failures (test passes in isolation, flaky under check-sycl -j and on buildbot). Match both linker's phrasing.

Fix flaky fail in check-sycl:
ld: error: undefined symbol: sycl::_V1::detail::getKernelNameHelper(sycl::_V1::detail::KernelIdentity<NotAKernel>)
CMPLRLLVM-76620

### CODE REVIEW

**Review by cperkinsintel — APPROVED** [review]

**Comment by wenju-he** [comment]
@intel/llvm-gatekeepers please merge, thanks.
```
Timed Out Tests (1):
  SYCL :: Assert/assert_in_simultaneously_multiple_tus.cpp
```
is known issue: https://github.com/intel/llvm/issues/21023
