### ISSUE TITLE
Linux Pytorch build broken in 20260812 nightly

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#22940]
### Describe the bug

```
/__w/llvm/llvm/pytorch/build/_deps/repo-sycl-tla-src/include/cute/util/compat/launch_policy.hpp:116:3: error: constructor for 'compat::experimental::launch_policy<sycl::nd_range<3>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>, false>' must explicitly initialize the member '_range' which does not have a default constructor
  116 |   launch_policy(Ts... ts)
      |   ^
/__w/llvm/llvm/pytorch/build/_deps/repo-sycl-tla-src/include/cute/util/compat/launch_policy.hpp:154:9: note: in instantiation of function template specialization 'compat::experimental::launch_policy<sycl::nd_range<3>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>, false>::launch_policy<compat::experimental::launch_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>>, compat::experimental::kernel_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>>>' requested here
  154 |       : launch_policy(ts...) {
      |         ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_launch.h:1009:39: note: in instantiation of function template specialization 'compat::experimental::launch_policy<sycl::nd_range<3>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>, false>::launch_policy<compat::experimental::launch_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>>, compat::experimental::kernel_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>>>' requested here
 1009 |   compat::experimental::launch_policy policy1{
      |                                       ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_launch.h:1096:3: note: in instantiation of function template specialization 'cute::run_mha_bwd_specialized<cutlass::half_t, 128, 128, 128, 32, 4, 4, 4, false>' requested here
 1096 |   RUN_MHA_BWD_SPECIALIZED();
      |   ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_launch.h:1032:3: note: expanded from macro 'RUN_MHA_BWD_SPECIALIZED'
 1032 |   run_mha_bwd_specialized<        \
      |   ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_hdim128.cpp:22:3: note: in instantiation of function template specialization 'cute::run_mha_bwd_hdim128<cutlass::half_t, false>' requested here
   22 |   run_mha_bwd_hdim128<cute::half_t, false>(queue, params);
      |   ^
/__w/llvm/llvm/pytorch/build/_deps/repo-sycl-tla-src/include/cute/util/compat/launch_policy.hpp:165:9: note: member is declared here
  165 |   Range _range;
      |         ^
/__w/llvm/llvm/install/bin/../include/sycl/nd_range.hpp:28:37: note: 'sycl::nd_range<3>' declared here
   28 | template <int Dimensions = 1> class nd_range {
      |                                     ^
2 errors generated.
CMake Error at torch-xpu-ops-sycltla_gen_mha_bwd_hdim128.cpp.o.Release.cmake:153 (message):

```

https://github.com/intel/llvm/actions/runs/31664936246/job/94340824752

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

**Comment by sarnex** [comment]
Hey @KornevNikita, could this be caused by https://github.com/intel/llvm/pull/22908?

FYI @dvrogozh
