### ISSUE TITLE
SYCL branch is broken when built with `--disable-jit`

### ISSUE THREAD

**Issue by vinser52** [intel/llvm#19291]
### Describe the bug

The #18918 breaks the build when `--disable-jit` option is used.

### To reproduce

Build command to reproduce the issue:
```bash
python3 ../buildbot/configure.py --disable-jit --level_zero_adapter_version ALL -t RelWithDebInfo
python3 ../buildbot/compile.py
```

Error output:

```bash
[7/502] Building CXX object tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_image_impl.cpp.o
FAILED: tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_image_impl.cpp.o
/usr/bin/c++ -DCL_TARGET_OPENCL_VERSION=300 -DSYCL2020_DISABLE_DEPRECATION_WARNINGS -DXPTI_ENABLE_INSTRUMENTATION -DXPTI_STATIC_LIBRARY -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__DPCPP_ENABLE_UNFINISHED_KHR_EXTENSIONS -D__STDC_CONSTANT_MACROS -D__S
TDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__SYCL_INTERNAL_API -I/user/svinogra/llvm/build_debug/tools/sycl/source -I/user/svinogra/llvm/sycl/source -I/user/svinogra/llvm/build_debug/include -I/user/svinogra/llvm/llvm/include -I/user/svinogra/llvm/xpti/in
clude -I/user/svinogra/llvm/sycl/include -I/user/svinogra/llvm/unified-runtime/include -I/user/svinogra/llvm/build_debug/_deps/opencl-headers-src -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wex
tra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdele
te-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -Wall -Wextra -g -gsplit-dwarf -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -Wno-psabi -fn
o-omit-frame-pointer -std=c++17 -MD -MT tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_image_impl.cpp.o -MF tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_image_impl.cpp.o.d -o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/d
evice_image_impl.cpp.o -c /user/svinogra/llvm/sycl/source/detail/device_image_impl.cpp
In file included from /user/svinogra/llvm/sycl/source/detail/device_image_impl.cpp:9:
/user/svinogra/llvm/sycl/source/detail/device_image_impl.hpp:11:10: fatal error: JITBinaryInfo.h: No such file or directory
   11 | #include "JITBinaryInfo.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

```

### Environment

- OS: Linux

**Comment by uditagarwal97** [comment]
@jchlanda I think the shared nightly build was also broken by https://github.com/intel/llvm/pull/18918. See https://github.com/intel/llvm/actions/runs/16040866467/job/45261963457#step:9:16624
```
[7612/9622] Linking CXX shared library lib/libsycl-jit.so.21.0git
FAILED: lib/libsycl-jit.so.21.0git 
: && /usr/bin/g++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/__w/llvm/llvm/build/./lib  -Wl,--gc-sections -shared -Wl,-soname,libsycl-jit.so.21.0git -o lib/libsycl-jit.so.21.0git tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/translation/JITContext.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/translation/SPIRVLLVMTranslation.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/translation/Translation.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/materializer/MaterializerPipeline.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/materializer/Materializer.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/rtc/DeviceCompilation.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/rtc/ESIMD.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/rtc/RTC.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/helper/ConfigHelper.cpp.o tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/helper/ErrorHelper.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib:/__w/llvm/llvm/build/lib:"  lib/libclangCodeGen.so.21.0git  lib/libclangTooling.so.21.0git  lib/libLLVMSYCLPostLink.so.21.0git  lib/libLLVMNVPTXCodeGen.so.21.0git  lib/libLLVMNVPTXDesc.so.21.0git  lib/libLLVMNVPTXInfo.so.21.0git  lib/libLLVMAMDGPUCodeGen.so.21.0git  lib/libLLVMAMDGPUAsmParser.so.21.0git  lib/libLLVMAMDGPUDisassembler.so.21.0git  lib/libLLVMSPIRVCodeGen.so.21.0git  lib/libLLVMSPIRVDesc.so.21.0git  lib/libLLVMSPIRVInfo.so.21.0git  lib/libLLVMX86CodeGen.so.21.0git  lib/libLLVMX86AsmParser.so.21.0git  lib/libLLVMX86Desc.so.21.0git  lib/libLLVMX86Disassembler.so.21.0git  lib/libLLVMX86Info.so.21.0git  lib/libLLVMSPIRVLib.so.21.0git  lib/libSYCLJITPasses.so.21.0git  -Wl,--version-script=/__w/llvm/llvm/src/sycl-jit/jit-compiler/ld-version-script.txt  lib/libclangFrontend.so.21.0git  lib/libclangDriver.so.21.0git  lib/libclangSerialization.so.21.0git  lib/libLLVMOption.so.21.0git  lib/libclangBasic.so.21.0git  lib/libLLVMAMDGPUDesc.so.21.0git  lib/libLLVMAMDGPUInfo.so.21.0git  lib/libLLVMAMDGPUUtils.so.21.0git  lib/libLLVMPasses.so.21.0git  lib/libLLVMSYCLLowerIR.so.21.0git  lib/libLLVMipo.so.21.0git  lib/libLLVMLinker.so.21.0git  lib/libLLVMGenXIntrinsics.so.21.0git  lib/libLLVMScalarOpts.so.21.0git  lib/libLLVMInstCombine.so.21.0git  lib/libLLVMTarget.so.21.0git  lib/libLLVMTransformUtils.so.21.0git  lib/libLLVMBitWriter.so.21.0git  lib/libLLVMAnalysis.so.21.0git  lib/libLLVMIRReader.so.21.0git  lib/libLLVMBitReader.so.21.0git  lib/libLLVMCore.so.21.0git  lib/libLLVMMC.so.21.0git  lib/libLLVMTargetParser.so.21.0git  lib/libLLVMSupport.so.21.0git  -Wl,-rpath-link,/__w/llvm/llvm/build/lib && :
/usr/bin/ld: tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/rtc/DeviceCompilation.cpp.o: in function `jit_compiler::linkDeviceLibraries(llvm::Module&, llvm::opt::InputArgList const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, jit_compiler::BinaryFormat)':
DeviceCompilation.cpp:(.text._ZN12jit_compiler19linkDeviceLibrariesERN4llvm6ModuleERKNS0_3opt12InputArgListERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_12BinaryFormatE+0x1122): undefined reference to `clang::driver::toolchains::ROCMToolChain::ROCMToolChain(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&)'
/usr/bin/ld: DeviceCompilation.cpp:(.text._ZN12jit_compiler19linkDeviceLibrariesERN4llvm6ModuleERKNS0_3opt12InputArgListERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_12BinaryFormatE+0x113e): undefined reference to `clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames(llvm::opt::ArgList const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clang::driver::Action::OffloadKind, bool) const'
/usr/bin/ld: DeviceCompilation.cpp:(.text._ZN12jit_compiler19linkDeviceLibrariesERN4llvm6ModuleERKNS0_3opt12InputArgListERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_12BinaryFormatE+0x1313): undefined reference to `vtable for clang::driver::toolchains::AMDGPUToolChain'
/usr/bin/ld: tools/sycl-jit/jit-compiler/CMakeFiles/sycl-jit.dir/lib/rtc/DeviceCompilation.cpp.o: relocation R_X86_64_PC32 against undefined hidden symbol `_ZTVN5clang6driver10toolchains15AMDGPUToolChainE' can not be used when making a shared object
/usr/bin/ld: final link failed: bad value
```

**Comment by AlexeySachkov** [comment]
Looks to be resolved by #19302 and #19342, so I'm going to close it. Please re-open if this is still an issue
