### ISSUE TITLE
Compile fail when building compiler with icpx

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#22819]
### Describe the bug

Seeing new compile fail when using icpx to build intel/llvm

https://github.com/intel/llvm/actions/runs/30512702923/job/90907983082

```
FAILED: lib/libsycl.so.9.0.0-0 
: && /opt/intel/oneapi/compiler/2025.3/bin/icpx -fPIC -no-intel-lib -ffp-model=precise -fno-unroll-loops -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wmisleading-indentation -Wctad-maybe-unsupported -ffunction-sections -fdata-sections -Wno-covered-switch-default -Wall -Wextra -Werror -O3 -DNDEBUG  -shared  -Wl,-z,defs -Wl,-z,nodelete -Wl,--gc-sections -Wl,--dependency-file=tools/sycl/source/CMakeFiles/sycl.dir/link.d -Wl,-soname,libsycl.so.9 -o lib/libsycl.so.9.0.0-0 tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/backend.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/common_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/geometric_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/half_precision_math_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/integer_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/math_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/native_math_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/relational_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/adapter_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/allowlist.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/bindless_images.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/buffer_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/common.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/composite_device/composite_device.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/config.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/context_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_binary_image.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_filter.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_global_map.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_data.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_global_info.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_global_map_entry.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_image_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/error_handling/error_handling.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/event_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/filter_selector_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/global_handler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/graph_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/dynamic_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/node_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/helpers.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/handler_proxy.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/image_accessor_util.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/image_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/jit_compiler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/jit_device_binaries.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_compiler/kernel_compiler_opencl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_compiler/kernel_compiler_sycl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/get_device_kernel_info.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/get_kernel_info_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_kernel_info.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_program_cache.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_export.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_manager.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/platform_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/program_manager/program_manager.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/queue_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/os_util.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/persistent_device_code_cache.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/preview_marker.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/range_rounding.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/reduction.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/sampler_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/stream_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/syclbin.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/commands.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/leaves_collection.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/scheduler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/graph_processor.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/graph_builder.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/spec_constant_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/sycl_mem_obj_t.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/usm/usm_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/ur.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/util.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/xpti_registry.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/accessor.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/buffer.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/context.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/device.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/device_selector.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/enqueue_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/event.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/exception.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/exception_list.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/handler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/image.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/interop_handle.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/ipc_event.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/ipc_memory.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/ipc_physical_memory.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/kernel.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/kernel_bundle.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/physical_mem.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/platform.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/printers.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/queue.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/reusable_events.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/sampler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/stream.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/virtual_mem.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_pool_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/async_alloc.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_pool.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/memory_pool.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/posix_ur.cpp.o  -Wl,-rpath,:::::::  -ldl  lib/libur_loader.a  lib/libxpti.a  /usr/local/lib/libzstd.a  -Wl,--version-script=/__w/llvm/llvm/src/sycl/source/ld-version-script.txt  -ldl  lib/libur_adapter_level_zero.a  lib/libur_adapter_opencl.a  lib/libur_adapter_level_zero_v2.a  lib/libur_common.a  lib/libze_loader.a  lib/liblevel_zero_utils.a  lib/libumf.a  lib/libumf_coarse.a  lib/libumf_ba.a  lib/libumf_utils.a  -lstdc++fs  hwloc_targ-prefix/lib/libhwloc.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoGSYM.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoBTF.a  lib/libLLVMObject.a  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoDWARFLowLevel.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  -ldl  /usr/local/lib/libzstd.a  -lrt  -lm  /usr/lib/x86_64-linux-gnu/libz.so  lib/libLLVMDemangle.a && :
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc_internal_distances_dup':
distances.c:(.text+0x36e): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x3e0): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x445): undefined reference to `_intel_fast_memset'
/usr/bin/ld: distances.c:(.text+0x499): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x4a9): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc__groups_by_distances':
distances.c:(.text+0x14d1): undefined reference to `_intel_fast_memset'
/usr/bin/ld: distances.c:(.text+0x1c98): undefined reference to `_intel_fast_memset'
/usr/bin/ld: distances.c:(.text+0x1dd3): undefined reference to `_intel_fast_memset'
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc_distances_add_values':
distances.c:(.text+0x258e): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x259e): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc__distances_get':
distances.c:(.text+0x3190): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x31c3): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x3227): undefined reference to `_intel_fast_memset'
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(topology-linux.o): in function `hwloc_linux_set_tid_cpubind':

```

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

- OS: [e.g Windows/Linux]
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. the output of `sycl-ls --verbose`]

**Comment by sarnex** [comment]
@kswiecicki @pbalcer Could this be caused by https://github.com/intel/llvm/pull/21845? 

I see we have some handling for similar cases already (ex [here](https://github.com/intel/llvm/blob/450b92d936afa993501c3accd8d09d0df3393baf/unified-runtime/cmake/helpers.cmake#L120), maybe we need something new?

**Comment by pbalcer** [comment]
> [@kswiecicki](https://github.com/kswiecicki) [@pbalcer](https://github.com/pbalcer) Could this be caused by [#21845](https://github.com/intel/llvm/pull/21845)?
> 
> I see we have some handling for similar cases already (ex [here](https://github.com/intel/llvm/blob/450b92d936afa993501c3accd8d09d0df3393baf/unified-runtime/cmake/helpers.cmake#L120), maybe we need something new?

I thought I already fixed it here:
https://github.com/intel/llvm/pull/22541

I have the workaround gated on `UR_ENABLE_SYMBOLIZER`, so maybe this is a build without sanitizers enabled? Anyway, it seems that this:
```
        # Symbolizer dependencies may emit calls to
        # _intel_fast_memcpy/_intel_fast_memset. Those are normally provided
        # by libirc, but libsycl / ur doesn't link them. Use stubs forwarding to
        # plain memcpy/memset. The stub is compiled with -no-intel-lib, which
        # add_ur_target_compile_options() already applies to the whole target.
        if(CMAKE_C_COMPILER_ID STREQUAL "IntelLLVM")
            target_sources(ur_loader PRIVATE
                ${CMAKE_CURRENT_SOURCE_DIR}/layers/sanitizer/sanitizer_common/linux/intel_fast_mem_stub.c
            )
        endif()
```
should be moved to some common part of UR CMake.

**Comment by sarnex** [comment]
This just started failing recently in the most recent nightly, so it seems to be a new issue. Here is the full cmake command

`
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON '-DLLVM_TARGETS_TO_BUILD=host;SPIRV;NVPTX' '-DLLVM_EXTERNAL_PROJECTS=sycl;llvm-spirv;opencl;xpti;xptifw;;libdevice;sycl-jit' -DLLVM_EXTERNAL_SYCL_SOURCE_DIR=/__w/llvm/llvm/src/sycl -DLLVM_EXTERNAL_LLVM_SPIRV_SOURCE_DIR=/__w/llvm/llvm/src/llvm-spirv -DLLVM_EXTERNAL_XPTI_SOURCE_DIR=/__w/llvm/llvm/src/xpti -DXPTI_SOURCE_DIR=/__w/llvm/llvm/src/xpti -DLLVM_EXTERNAL_XPTIFW_SOURCE_DIR=/__w/llvm/llvm/src/xptifw -DLLVM_EXTERNAL_LIBDEVICE_SOURCE_DIR=/__w/llvm/llvm/src/libdevice -DLLVM_EXTERNAL_SYCL_JIT_SOURCE_DIR=/__w/llvm/llvm/src/sycl-jit '-DLLVM_ENABLE_PROJECTS=clang;sycl;llvm-spirv;opencl;xpti;xptifw;;libdevice;sycl-jit;clang-tools-extra' -DSYCL_BUILD_UR_HIP_PLATFORM=AMD -DLLVM_BUILD_TOOLS=ON -DLLVM_ENABLE_ZSTD=FORCE_ON -DLLVM_USE_STATIC_ZSTD=ON -DSYCL_ENABLE_WERROR=ON -DCMAKE_INSTALL_PREFIX=/__w/llvm/llvm/build/install -DSYCL_INCLUDE_TESTS=ON -DLLVM_ENABLE_DOXYGEN=OFF -DLLVM_ENABLE_SPHINX=OFF -DBUILD_SHARED_LIBS=OFF -DSYCL_ENABLE_XPTI_TRACING=ON -DLLVM_ENABLE_LLD=OFF -DLLVM_SPIRV_ENABLE_LIBSPIRV_DIS=ON -DXPTI_ENABLE_WERROR=ON -DSYCL_CLANG_EXTRA_FLAGS= '-DSYCL_ENABLE_BACKENDS=opencl;level_zero_v2;level_zero' -DSYCL_ENABLE_EXTENSION_JIT=ON -DSYCL_ENABLE_MAJOR_RELEASE_PREVIEW_LIB=ON -DBUG_REPORT_URL=https://github.com/intel/llvm/issues -DLLVM_ENABLE_RUNTIMES=compiler-rt -DRUNTIMES_nvptx64-nvidia-cuda_LLVM_ENABLE_RUNTIMES=libclc '-DLLVM_RUNTIME_TARGETS=default;nvptx64-nvidia-cuda' /__w/llvm/llvm/src/llvm -DCMAKE_INSTALL_PREFIX=/__w/llvm/llvm/toolchain '-DCMAKE_C_FLAGS=-no-intel-lib -ffp-model=precise -fno-unroll-loops' '-DCMAKE_CXX_FLAGS=-no-intel-lib -ffp-model=precise -fno-unroll-loops' -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DLLVM_INSTALL_UTILS=ON -DSYCL_UR_FORCE_FETCH_LEVEL_ZERO=ON
`

Note the compiler is selected through envvars here, `CC=icx CXX=icpx`

**Comment by pbalcer** [comment]
I think I know why. This https://github.com/intel/llvm/pull/21845 pulled in static libhwloc into libsycl, icpx used its memcpy/memset variants for libhwloc, which doesn't resolve now. Like I said, I think we need to move the fix I did previously just for the sanitizer to UR common. @kswiecicki can you do that?

**Comment by sarnex** [comment]
Thanks for the quick investigation! There's no rush for a fix, however it's possible we hit something similar when we pull down to the internal compiler, so having a fix we could cherry pick quickly would be useful.

**Comment by kswiecicki** [comment]
I've made a fix for this [here](https://github.com/intel/llvm/pull/22838).

**Comment by sarnex** [comment]
Sorry to say this is still failing in the latest nightly:

```
FAILED: lib/libsycl.so.9.0.0-0 
: && /opt/intel/oneapi/compiler/2025.3/bin/icpx -fPIC -no-intel-lib -ffp-model=precise -fno-unroll-loops -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wmisleading-indentation -Wctad-maybe-unsupported -ffunction-sections -fdata-sections -Wno-covered-switch-default -Wall -Wextra -Werror -O3 -DNDEBUG  -shared  -Wl,-z,defs -Wl,-z,nodelete -Wl,--gc-sections -Wl,--dependency-file=tools/sycl/source/CMakeFiles/sycl.dir/link.d -Wl,-soname,libsycl.so.9 -o lib/libsycl.so.9.0.0-0 tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/backend.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/common_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/geometric_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/half_precision_math_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/integer_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/math_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/native_math_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/builtins/relational_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/adapter_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/allowlist.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/bindless_images.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/buffer_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/common.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/composite_device/composite_device.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/config.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/context_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_binary_image.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_filter.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_global_map.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_data.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_global_info.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_global_map_entry.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_image_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/error_handling/error_handling.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/event_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/filter_selector_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/global_handler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/graph_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/dynamic_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/node_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/helpers.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/handler_proxy.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/image_accessor_util.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/image_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/jit_compiler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/jit_device_binaries.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_compiler/kernel_compiler_opencl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_compiler/kernel_compiler_sycl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/get_device_kernel_info.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/get_kernel_info_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/device_kernel_info.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/kernel_program_cache.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_export.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_manager.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/platform_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/program_manager/program_manager.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/queue_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/os_util.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/persistent_device_code_cache.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/preview_marker.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/range_rounding.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/reduction.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/sampler_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/stream_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/syclbin.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/commands.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/leaves_collection.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/scheduler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/graph_processor.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/scheduler/graph_builder.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/spec_constant_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/sycl_mem_obj_t.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/usm/usm_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/ur.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/util.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/xpti_registry.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/accessor.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/buffer.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/context.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/device.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/device_selector.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/enqueue_functions.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/event.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/exception.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/exception_list.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/handler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/image.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/interop_handle.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/ipc_event.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/ipc_memory.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/ipc_physical_memory.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/kernel.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/kernel_bundle.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/physical_mem.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/platform.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/printers.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/queue.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/reusable_events.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/sampler.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/stream.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/virtual_mem.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_pool_impl.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/async_alloc.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/memory_pool.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/graph/memory_pool.cpp.o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/posix_ur.cpp.o  -Wl,-rpath,:::::::  -ldl  lib/libur_loader.a  lib/libxpti.a  /usr/local/lib/libzstd.a  -Wl,--version-script=/__w/llvm/llvm/src/sycl/source/ld-version-script.txt  -ldl  lib/libur_adapter_level_zero.a  lib/libur_adapter_opencl.a  lib/libur_adapter_level_zero_v2.a  lib/libur_common.a  lib/libze_loader.a  lib/liblevel_zero_utils.a  lib/libumf.a  lib/libumf_coarse.a  lib/libumf_ba.a  lib/libumf_utils.a  -lstdc++fs  hwloc_targ-prefix/lib/libhwloc.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoGSYM.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoBTF.a  lib/libLLVMObject.a  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoDWARFLowLevel.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  -ldl  /usr/local/lib/libzstd.a  -lrt  -lm  /usr/lib/x86_64-linux-gnu/libz.so  lib/libLLVMDemangle.a && :
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc_internal_distances_dup':
distances.c:(.text+0x36e): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x3e0): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x445): undefined reference to `_intel_fast_memset'
/usr/bin/ld: distances.c:(.text+0x499): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: distances.c:(.text+0x4a9): undefined reference to `_intel_fast_memcpy'
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc__groups_by_distances':
distances.c:(.text+0x14d1): undefined reference to `_intel_fast_memset'
/usr/bin/ld: distances.c:(.text+0x1c98): undefined reference to `_intel_fast_memset'
/usr/bin/ld: distances.c:(.text+0x1dd3): undefined reference to `_intel_fast_memset'
/usr/bin/ld: hwloc_targ-prefix/lib/libhwloc.a(distances.o): in function `hwloc_distances_add_values':
<a ton more>
```

https://github.com/intel/llvm/actions/runs/30783781608/job/91593354526

@kswiecicki Can you please take another look? Thanks!

**Comment by sarnex** [comment]
FYI @kswiecicki this is still failing in the nightly even with the latest changes: https://github.com/intel/llvm/actions/runs/31455708850/job/93668913755

**Comment by bratpiorka** [comment]
fixed by #22973
