### PR TITLE
[SYCL] Restore the nd_range default constructor

### LINKED ISSUE #22940: Linux Pytorch build broken in 20260812 nightly
### Describe the bug

```
/__w/llvm/llvm/pytorch/build/_deps/repo-sycl-tla-src/include/cute/util/compat/launch_policy.hpp:116:3: error: constructor for 'compat::experimental::launch_policy<sycl::nd_range<3>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>, false>' must explicitly initialize the member '_range' which does not have a default constructor
  116 |   launch_policy(Ts... ts)
      |   ^
/__w/llvm/llvm/pytorch/build/_deps/repo-sycl-tla-src/include/cute/util/compat/launch_policy.hpp:154:9: note: in instantiation of function template specialization 'compat::experimental::launch_policy<sycl::nd_range<3>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>, false>::launch_policy<compat::experimental::launch_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>>, compat::experimental::kernel_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>>>' requested here
  154 |       : launch_policy(ts...) {
      |         ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_launch.h:1009:39: note: in instantiation of function template specialization 'compat::experimental::launch_policy<sycl::nd_range<3>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>, sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>, false>::launch_policy<compat::experimental::launch_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::work_group_scratch_size>>>, compat::experimental::kernel_properties<sycl::ext::oneapi::experimental::properties<sycl::ext::oneapi::experimental::detail::properties_type_list<sycl::ext::oneapi::experimental::property_value<sycl::ext::oneapi::experimental::sub_group_size_key, std::integral_constant<unsigned int, 16>>>>>>' requested here
 1009 |   compat::experimental::launch_policy policy1{
      |                                       ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_launch.h:1096:3: note: in instantiation of function template specialization 'cute::run_mha_bwd_specialized<cutlass::half_t, 128, 128, 128, 32, 4, 4, 4, false>' requested here
 1096 |   RUN_MHA_BWD_SPECIALIZED();
      |   ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_launch.h:1032:3: note: expanded from macro 'RUN_MHA_BWD_SPECIALIZED'
 1032 |   run_mha_bwd_specialized<        \
      |   ^
/__w/llvm/llvm/pytorch/third_party/torch-xpu-ops/src/ATen/native/transformers/xpu/flash_attn/sycltla/mha_bwd_hdim128.cpp:22:3: note: in instantiation of function template specialization 'cute::run_mha_bwd_hdim128<cutlass::half_t, false>' requested here
   22 |   run_mha_bwd_hdim128<cute::half_t, false>(queue, params);
      |   ^
/__w/llvm/llvm/pytorch/build/_deps/repo-sycl-tla-src/include/cute/util/compat/launch_policy.hpp:165:9: note: member is declared here
  165 |   Range _range;
      |         ^
/__w/llvm/llvm/install/bin/../include/sycl/nd_range.hpp:28:37: note: 'sycl::nd_range<3>' declared here
   28 | template <int Dimensions = 1> class nd_range {
      |                                     ^
2 errors generated.
CMake Error at torch-xpu-ops-sycltla_gen_mha_bwd_hdim128.cpp.o.Release.cmake:153 (message):

```

https://github.com/intel/llvm/actions/runs/31664936246/job/94340824752

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arnavprabhu**
Fixes #22940

## Problem

PR #22908 removed `nd_range`'s default constructor (`nd_range() = default;`)
to align the class with the SYCL 2020 specification, which does not declare
one. That broke code which default-constructs an `nd_range` and assigns it
later. The most visible casualty is CuTe's `launch_policy`
(`include/cute/util/compat/launch_policy.hpp`), used by PyTorch's XPU
flash-attention kernels, which holds an `nd_range<3>` member that gets
default-initialized:

```
error: constructor for 'compat::experimental::launch_policy<sycl::nd_range<3>, ...>'
must explicitly initialize the member '_range' which does not have a default constructor
```

## Change

Restore `nd_range() = default;`. All three members (`globalSize`, `localSize`,
`offset`) are `range`/`id` objects, both of which keep zero-initializing
default constructors, so a default-constructed `nd_range` is well-defined and
produces zeroed ranges and offset.

## Test plan

- Extended `sycl/test/basic_tests/nd_range.cpp` to default-construct an
  `nd_range<3>` and assert the constituent ranges and offset are
  zero-initialized.

### CODE REVIEW

File: sycl/include/sycl/nd_range.hpp [hunk 1]
```diff
@@ -62,6 +62,12 @@ template <int Dimensions = 1> class nd_range {
   nd_range(nd_range<Dimensions> &&rhs) = default;
   nd_range<Dimensions> &operator=(const nd_range<Dimensions> &rhs) = default;
   nd_range<Dimensions> &operator=(nd_range<Dimensions> &&rhs) = default;
+
+  // nd_range has no default constructor in SYCL 2020, but one is kept as an
```
Comment (KornevNikita) [inline sycl/include/sycl/nd_range.hpp]: I hope we'll add this to the spec in https://github.com/KhronosGroup/SYCL-Docs/issues/1043, otherwise we'll proceed with the extension to declare this. Therefore I'd suggest to drop this comment and update the comment in the test.

Comment (arnavprabhu) [reply sycl/include/sycl/nd_range.hpp]: Done — I removed the comment from the header and changed the test comment to describe only the behavior being checked, without calling the constructor an extension.

**Comment by KornevNikita** [comment]
Note for reviewers - please do not merge it right now. We need a few days to discuss this and decide if we want to put it to SYCL 2020 (most likely) or to create a oneapi extension.

**Comment by dvrogozh** [comment]
> if we want to put it to SYCL 2020 (most likely) or to create a oneapi extension.

Please, keep me updated on this.

**Comment by KornevNikita** [comment]
Not sure how long I'll take to update the [spec](https://github.com/KhronosGroup/SYCL-Docs/issues/1043). I've added macros to keep this until the next major release. I suggest to proceed that way, hope it will be added to the spec soon, so I'll remove the macros.

P.S. now it should look like we didn't remove this, but just guarded to be removed prior to next major release.

**Comment by KornevNikita** [comment]
@KseniyaTikhomirova could you take a look please? This change is desired by sycl-tla team.

**Review by KseniyaTikhomirova — APPROVED** [review]

File: sycl/include/sycl/nd_range.hpp [hunk 2]
```diff
@@ -62,6 +62,11 @@ template <int Dimensions = 1> class nd_range {
   nd_range(nd_range<Dimensions> &&rhs) = default;
   nd_range<Dimensions> &operator=(const nd_range<Dimensions> &rhs) = default;
   nd_range<Dimensions> &operator=(nd_range<Dimensions> &&rhs) = default;
+
+#ifndef __INTEL_PREVIEW_BREAKING_CHANGES
```
Comment (dvrogozh) [inline sycl/include/sycl/nd_range.hpp:66]: On pytorch side we can't accept this solution in the release version of the compiler, neither closed source DPC++ nor open source dpclang. We need this resolved before the next release. Can you educate me what exactly is an issue to step out from the spec on this matter and continue to have `nd_range` default compiler defined?

**Review by dvrogozh — CHANGES_REQUESTED** [review]

File: sycl/include/sycl/nd_range.hpp (hunk 2 above)
Comment (KornevNikita) [reply sycl/include/sycl/nd_range.hpp:66]: @dvrogozh you mean you can't accept this macro? By the next release you mean 7.3.0? Because 7.2.0 will contain this ctor. I believe we'll resolve this by 7.3.0, this is just to unblock folks that need this right now.

> Can you educate me what exactly is an issue to step out from the spec on this matter and continue to have nd_range default compiler defined?

@gmlueck do you think we can restore this right now without any guards? Note - we had it for a long time, but I removed it recently, so it won't be like adding a new API  but rather restoring the existed one.

Comment (dvrogozh) [reply sycl/include/sycl/nd_range.hpp:66]: Pytorch stopped using preview macro long time ago and it was an effort dedicated to that due to Pytorch being production environment. And we don't want to introduce it again.

>this is just to unblock folks that need this right now.

This solution is OK as intermediate engineering solution, but that's showstopper from my perspective for the next release which seems to be 7.3.0 per your comment.

Comment (KornevNikita) [reply sycl/include/sycl/nd_range.hpp:66]: This ctor is added under "if not defined INTEL_PREVIEW...", so it'll be available even in 7.3.0, but might be removed prior to 8.0.0. I believe we'll add it to SYCL 2020 or create a oneapi extension by this time.

Does it work for you?

Comment (dvrogozh) [reply sycl/include/sycl/nd_range.hpp:66]: oh, ok, I misread the condition looking into the PR early morning. Then reformulating the concern, this PR is fine right now but gives a risk to the next major release 8.0.0 if you will decide to drop this ctor.

Comment (gmlueck) [reply sycl/include/sycl/nd_range.hpp:66]: I am not opposed to this change, but it might make sense to wait until later this week if there is no hurry.  I'm hoping to bring KhronosGroup/SYCL-Docs#1043 up for discussing on Thursday of this week.  If the Khronos WG decides to add the default constructor as an "errata" fix, then we won't need this PR at all.  We can just keep the default constructor as it is now.

Comment (dvrogozh) [reply sycl/include/sycl/nd_range.hpp:66]: Without this change intel/llvm pytorch CI is blocked. Longer it's broken more risk for other issues to appear unnoticed contributing to the triage bucket.

Comment (gmlueck) [reply sycl/include/sycl/nd_range.hpp:66]: Maybe I'm reading this PR wrong.  I thought it was just *removing* the default constructor in `-fpreview-breaking-changes` mode?  There's no change at all in the regular mode, right?

@dvrogozh, I think you said above that PyTorch doesn't use the `-fpreview-breaking-changes` mode.  If my understanding about this PR is correct, I don't think it will have any effect on PyTorch at all.

Comment (dvrogozh) [reply sycl/include/sycl/nd_range.hpp:66]: I am talking about pytorch CI defined in this intel/llvm repository. You have a workflow which validates most recent builds of the dpclang compiler with the pytorch. See https://github.com/intel/llvm/blob/sycl/.github/workflows/sycl-pytorch-build-and-test.yml.

Comment (gmlueck) [reply sycl/include/sycl/nd_range.hpp:66]: I understand now.  Sorry, I didn't read the PR description closely enough.  I see now that this is undoing the recent change in #22908, which removed that default constructor.

Feel free to merge this PR now if you want.  If the WG decides later to add the default constructor, we can make another PR to remove the `#ifndef`.

**Comment by KornevNikita** [comment]
Hi @arnavprabhu,
Please check out https://llvm.org/docs/DeveloperPolicy.html#email-addresses - you'd have to change your Github account setting to allow committing from your personal/company email address. We don't allow committing from anonymous email addresses (like from noreply.github.com). Just changing your Github account settings should suffice - you don't have update the commits to include your personal email.
Thanks

**Comment by arnavprabhu** [comment]
Hi @KornevNikita,

I’ve updated my GitHub email settings accordingly. Please let me know if there’s anything else I need to address on the PR.

Thanks,
Arnav
