### ISSUE TITLE
Compiler error at CUDA Plugin pi_cuda.cpp

### ISSUE THREAD

**Issue by jandrovins** [intel/llvm#8750]
**Describe the bug**
While compiling from source, an error occurred while compiling `llvm/sycl/plugins/cuda/pi_cuda.cpp`.

> `llvm/sycl/plugins/cuda/pi_cuda.cpp:1957:35: error: use of undeclared identifier 'cuDeviceGetUuid_v2'; did you mean 'cuDeviceGetUuid'?
      sycl::detail::pi::assertion(cuDeviceGetUuid_v2(&uuid, device->get()) ==
                                  ^~~~~~~~~~~~~~~~~~
                                  cuDeviceGetUuid`

**To Reproduce**

1. Run configure.py: `CUDA_LIB_PATH=/usr/local/cuda-10.2/lib64/stubs/ CC=clang CXX=clang++ python $DPCPP_HOME/llvm/buildbot/configure.py --cuda --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2" --cmake-gen "Ninja" -o ./build-ibm --host-target PowerPC --use-lld`
2. Try to compile: `CUDA_LIB_PATH=/usr/local/cuda-10.2/lib64/stubs/ CC=clang CXX=clang++ python $DPCPP_HOME/llvm/buildbot/compile.py -o ./build-ibm -j 40`
3. While compiling the error above occurred. By reading the relevant [code snippet](https://github.com/intel/llvm/blob/a97afef4c56e571e935797d2c783ae39002ee7fb/sycl/plugins/cuda/pi_cuda.cpp#L1957) I guess that the reason for this error is that since I do not have a version of CUDA above 11.4 then `cuDeviceGetUuid_v2` is not available at compile time.

**Environment (please complete the following information):**

- OS: RHEL 7.5
- Target device and vendor: IBM Power CPU and Nvidia Volta V100.
- DPC++ version: Commit hash from git log: 10e07a38ae57e2312a44cc7aa1a6999b2813fb14
- Dependencies version: cuda 10.2

**Additional context**
N/A

**Comment by steffenlarsen** [comment]
Thank you for reporting this, @jandrovins!

Looks like the dependence on `cuDeviceGetUuid_v2` was introduced in https://github.com/intel/llvm/pull/8203. @npmiller - Do you think it would be sufficient if we change the conditional picking the version of `cuDeviceGetUuid` to use to instead be based on the `CUDA_VERSION` macro?

**Comment by npmiller** [comment]
Oh that's a good catch, yeah I think it should be sufficient to use a version macro instead.

**Comment by zjin-lcf** [comment]
Thank you for reporting the issue. User may be unwilling to upgrade their CUDA SDK. 
Is it ok to remove the "v2" call and call the "v1" for any Cuda version? Thanks.

**Comment by steffenlarsen** [comment]
https://github.com/intel/llvm/pull/8765 should address this issue. @jandrovins - Can you please confirm?

**Comment by steffenlarsen** [comment]
Thank you, @jandrovins! Closing this as fixed with https://github.com/intel/llvm/pull/8765.
