### PR TITLE
[UR] Fix PR #17684 - change in logs

### PR DESCRIPTION
**Pull request by mateuszpn**
Fix of compilation errors caused by merge of https://github.com/intel/llvm/pull/17684

### CODE REVIEW

**Review by kbenzie — APPROVED** [review]

**Review by ldrumm — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
Can this be merged? We don't need to wait for all the CI to finish here as unblocking other people is more important.

**Review by pbalcer — APPROVED** [review]
