### ISSUE TITLE
[SYCL] build is broken in kernel_program_cache.hpp

### ISSUE THREAD

**Issue by smaslov-intel** [intel/llvm#9168]
It appears that SYCL build is broken after https://github.com/intel/llvm/pull/8958
E.g. https://github.com/intel/llvm/actions/runs/4770018641/jobs/8480994136?pr=9153#step:7:3268

> D:\github\_work\llvm\llvm\src\sycl\source\detail/kernel_program_cache.hpp(86): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\github\_work\llvm\llvm\src\sycl\source\detail/kernel_program_cache.hpp(86): error C2146: syntax error: missing '>' before identifier 'KernelArgMask'

**Comment by smaslov-intel** [comment]
It appears few includes were missing, adding them in https://github.com/intel/llvm/pull/9169
