### ISSUE TITLE
Build failure in CI test due to HostPtr=null in memcpy

### ISSUE THREAD

**Issue by asudarsa** [intel/llvm#10380]
**Describe the bug**
In sycl/source/detail/sycl_mem_obj_t.hpp, there is a memcpy call that fails during build as follows:
`
[2023-07-14T04:10:16.104Z] /netbatch/donb1156623_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Build_PR_RHEL/llvm.src/sycl/source/detail/sycl_mem_obj_t.hpp:195:18: error: argument 2 null where non-null expected [-Werror=nonnull]
`
This failure is seen in https://github.com/intel/llvm/pull/10379 which has only test update.
Full log: http://icl-jenkins2.sc.intel.com:8080/blue/rest/organizations/jenkins/pipelines/SYCL_CI/pipelines/intel/pipelines/Build_PR_RHEL/runs/6462/log/?start=0

**To Reproduce**
Please look at full log provided above.

**Additional context**
https://github.com/intel/llvm/pull/10334 seems to be a possible reason.

Thanks
