### PR TITLE
[SYCL][E2E] Use configure_lit_site_cfg in in-tree builds

### PR DESCRIPTION
**Pull request by frasercrmck**
This provides the added benefit that it will automatically map the config paths from the build directories to the corresponding source ones in `llvm-lit`. With this, one should be able to run lit tests directly from source paths.

Note also that this changes the configured cfg file's name from `lit.site.cfg` to `lit.site.cfg.py`, but this aligns us with the predominant style across the llvm project.

### CODE REVIEW

**Comment by frasercrmck** [comment]
ping, maybe @aelovikov-intel?

**Comment by aelovikov-intel** [comment]
Thanks for pinging me, this one is great! I've been wondering if that can be achieved but didn't have time post test-suite move to look into it myself.

That said, it only works for the non-standalone configuration (when we configure both the compiler/RT and the E2E tests in a single invocation). The standalone configuration used in the CI (both here and a different flavor internally) breaks as can be seen by the failing pre-commit checks in this PR.

I think we need to guard the fix with 

```
if(SYCL_TEST_E2E_STANDALONE)
```

and use the old code for the `else` path.

**Comment by aelovikov-intel** [comment]
Also, it might make sense to modify `sycl/test-e2e/README.md#build-and-run-tests` to describe that benefit when using single cmake configuration.

File: sycl/test-e2e/README.md [hunk 1]
```diff
@@ -67,6 +67,19 @@ CC=<> CXX=<> python llvm/buildbot/configure.py -o build ... \
   --cmake-opt=-DSYCL_E2E_TESTS_LIT_FLAGS="--param;dump_ir=True"``
 ```
 
+In a workspace build, individual tests or groups of tests can be conveniently
+run directly from their source paths, using the configured `llvm-lit` script:
+
+```
+# Implicitly uses cmake parameters SYCL_BE and SYCL_TARGET_DEVICES, detailed
+# below
+build/bin/llvm-lit -sv sycl/test-e2e/Basic/aspects.cpp
```
Comment (aelovikov-intel) [inline sycl/test-e2e/README.md:76]: Wow, that's even better than I hoped for. Thanks a lot!

File: sycl/test-e2e/README.md [hunk 2]
```diff
@@ -56,8 +56,8 @@ cmake -G Ninja ...
 ninja check-sycl-e2e
 ```
 
-In addition to this standalone configuration one can enable `check-sycl-e2e`
-target for the sycl-toolchain workspace/build by specifying
+In addition to this, in a non-standalone configuration one can enable
+`check-sycl-e2e` target for the sycl-toolchain workspace/build by specifying
```
Comment (aelovikov-intel) [inline sycl/test-e2e/README.md:60]: >  I think it was a mistake in the old readme, but please check my change in case I'm wrong here.

Just a non-native English speaker and probably a missing comma. No ambiguity after you change, so thanks for that.

**Review by aelovikov-intel — APPROVED** [review]

File: sycl/test-e2e/README.md (hunk 2 above)
Comment (frasercrmck) [reply sycl/test-e2e/README.md:60]: NP! The only thing I was mulling over locally was the use of "non-standalone" vs "in-tree". Do you have any preference? I was actually going to go for "in-tree" but forgot to push.

Comment (aelovikov-intel) [reply sycl/test-e2e/README.md:60]: I don't, either is good enough but not perfect :D

**Comment by aelovikov-intel** [comment]
CI Failures:

L0 GEN9 Linux - not started, infrastructure problem?
OCL GEN9/CPU:
```SYCL :: Regression/device_num.cpp```

```
/__w/llvm/llvm/llvm/sycl/test-e2e/Regression/device_num.cpp:29:15: error: no member named 'ext_oneapi_unified_runtime' in 'sycl::backend'
    {backend::ext_oneapi_unified_runtime, "ext_oneapi_unified_runtime"},
     ~~~~~~~~~^
```

could it be caused by https://github.com/intel/llvm/pull/9013? @smaslov-intel @jandres742 

ESIMD: known issue, investigation is being tracked in an internal bug report
Windows: Likely known issue with a mis-configured runner.

@intel/llvm-gatekeepers , failures seem unrelated, can we merge this PR?

**Comment by jandres742** [comment]
> 

@aelovikov-intel : right, please rebase so you incorporate those changes and that error should go away.

File: sycl/test-e2e/README.md (hunk 2 above)
Comment (frasercrmck) [reply sycl/test-e2e/README.md]: Fair enough. Since I've had to rebase to try and make some of these CI failures, I've gone with "in-tree" just to help unify the language somewhat.

**Comment by frasercrmck** [comment]
Looks like most of the failures have indeed gone away, except for Windows L0 GEN12

File: sycl/test-e2e/README.md [hunk 3]
```diff
@@ -67,6 +67,19 @@ CC=<> CXX=<> python llvm/buildbot/configure.py -o build ... \
   --cmake-opt=-DSYCL_E2E_TESTS_LIT_FLAGS="--param;dump_ir=True"``
 ```
 
+In an in-tree build, individual tests or groups of tests can be conveniently
+run directly from their source paths, using the configured `llvm-lit` script:
+
+```
+# Implicitly uses cmake parameters SYCL_BE and SYCL_TARGET_DEVICES, detailed
+# below
```
Comment (aelovikov-intel) [inline sycl/test-e2e/README.md:75]: It seems it requires specifying them manually, in addition to `SYCL_TEST_E2E_TARGETS` above. Maybe worth adding a note somewhere here?
