### ISSUE TITLE
post-commit fail on Windows: use of overloaded operator is ambiguous

### ISSUE THREAD

**Issue by pvchupin** [intel/llvm#6142]
Started at the merge of pulldown from community: https://github.com/intel/llvm/runs/6377899714?check_suite_focus=true

```
d:\github\_work\llvm\llvm\build\bin\..\include\sycl\CL/sycl/half_type.hpp:390:17: error: use of overloaded operator '-' is ambiguous (operand type 'const sycl::detail::half_impl::StorageT' (aka 'const sycl::detail::host_half_impl::half_v2'))
    return half(-other.Data);
                ^~~~~~~~~~~

...

d:\github\_work\llvm\llvm\build\bin\..\include\sycl\CL/sycl/half_type.hpp:574:6: error: use of overloaded operator '==' is ambiguous (with operand types 'const sycl::detail::half_impl::StorageT' (aka 'const sycl::detail::host_half_impl::half_v2') and 'const sycl::detail::half_impl::StorageT')
  OP(==)
  ~~~^~~
```

There is unfortunate collision of 2 changes merged in parallel:

* https://github.com/intel/llvm/pull/6061
* [ad47114ad8500c78046161d492ac13a8e3e610eb](https://github.com/intel/llvm/commit/ad47114ad8500c78046161d492ac13a8e3e610eb)

Based on discussion in https://reviews.llvm.org/D124613 there is a discussion on some similar issue, which hopefully is going to be fixed soon (or patch reverted).

I'm going to revert ad47114ad8500c78046161d492ac13a8e3e610eb meanwhile to recover post-commit.
It seems nothing is wrong with https://github.com/intel/llvm/pull/6061

**Comment by pvchupin** [comment]
Tagging @AidanBeltonS, @steffenlarsen

**Comment by pvchupin** [comment]
Original change was reverted in upstream at e0fcdf5496ca686c8cebb63b63af86e666b42ab3

**Comment by pvchupin** [comment]
With this
