### ISSUE TITLE
[XPTI] Include path not setup correctly when building pi-trace

### ISSUE THREAD

**Issue by Naghasan** [intel/llvm#4137]
**Describe the bug**

When building `pi-trace` with tip `sycl`, the include path to `xpti` seems to not be configured properly.

I end up with a
```
llvm/sycl/tools/pi-trace/pi_trace.cpp:13:10: fatal error: xpti_trace_framework.h: No such file or directory
   13 | #include "xpti_trace_framework.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I tried a fresh build and configured using the configure script in the buildbot folder (`python3 buildbot/configure.py -s . -o ../build -t Release --cuda`), but after this I end up with the path to opencl headers not being found:

```
llvm/sycl/include/CL/sycl/detail/cl.h:17:10: fatal error: CL/cl.h: No such file or directory
   17 | #include <CL/cl.h>
```

(I rely on the headers pulled by the project)

If I remove the `add_subdirectory(pi-trace)` from `sycl/tools` everything builds fine.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04 
- DPC++ version:  ea4b8a945b80c4e7f10cc98a92a8e4815dcb99d6

**Comment by bader** [comment]
This looks like a regression introduced by e239fdf791295e5f57b9bfb949150b67fe6a5412.
@alexbatashev, could you fix this ASAP, please?

**Comment by danchitnis** [comment]
Further error log info here:
https://github.com/intel/llvm/discussions/4050#discussioncomment-1022651

**Comment by rolandschulz** [comment]
I can confirm that reverting e239fdf fixes the problem. Why don't we revert that commit until the issue is resolved?

**Comment by bader** [comment]
Done by https://github.com/intel/llvm/pull/4144.
