### PR TITLE
[SSAF] Fix Expected return type in TypeConstrainedPointers deserialization (gcc 7.5.0)

### PR DESCRIPTION
**Pull request by KornevNikita**
GCC 7.5.0 fails to compile this code. Use explicit upcasts from std::unique_ptr to std::unique_ptr in deserializeSummary and deserializeAnalysisResult. This resolves a compilation error where llvm::Expected<std::unique_ptr> could not be constructed from unique_ptr of derived summary/result types.

---
See: https://github.com/llvm/llvm-project/pull/211331
This file has been renamed in the upstream. The PR above should fix the issue in the upstream.
This one is to fix the toolchain build with gcc 7.5.0 before pulldown.

### CODE REVIEW

**Comment by KornevNikita** [comment]
@intel/dpcpp-cfe-reviewers I’d really appreciate a quick review; the patch is trivial.

**Review by elizabethandrews — APPROVED** [review]
This looks ok to me but @premanandrao can  you also take a look so I am not missing any unexpected consequences

**Comment by sys-ce-bb** [comment]
@intel/llvm-gatekeepers please consider merging

**Review by premanandrao — APPROVED** [review]
Looks okay to me.
