### PR TITLE
[NFC][SYCL][L0] Fix a warning about unused parameter

### PR DESCRIPTION
**Pull request by HabKaffee**
This PR fixed error `error: unused parameter 'Properties' [-Werror,-Wunused-parameter]` in `sycl/plugins/level_zero/pi_level_zero.cpp` caused by https://github.com/intel/llvm/commit/644c61445dd40d01a0d1016e2df66aca161fd464

### CODE REVIEW

**Comment by bader** [comment]
@HabKaffee, please, follow [contribution guide](https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md) to draw PRs.

**Comment by HabKaffee** [comment]
@bader Sure. I hope now it's ok.

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> @bader Sure. I hope now it's ok.

I changed "[SYCL][CI] Fix compilation error in post-commit testing" to "[NFC][SYCL][L0] Fix a warning about unused parameter".
- We apply [CI] tag for changes modifying scripts implementing CI system logic.
- Compiler emits a warning, so technically you are fixing a warning. The warning breaks post-commit build because CI scripts configures the build to treat all warnings in SYCL project as errors.

**Comment by HabKaffee** [comment]
> 

I got it. Thanks for clarifying.
