### ISSUE TITLE
 DiscardEvents/discard_events_l0_inorder.cpp failing on Linux Arc

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#14121]
### Describe the bug

https://github.com/intel/llvm/actions/runs/9450392481/job/26029562653

```

Command Output (stdout):
--
# RUN: at line 3
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/DiscardEvents/discard_events_l0_inorder.cpp -o /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/DiscardEvents/discard_events_l0_inorder.cpp -o /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 5
env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=0 ONEAPI_DEVICE_SELECTOR="level_zero:*" env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# executed command: env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=0 'ONEAPI_DEVICE_SELECTOR=level_zero:*' env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# .---command stdout------------
# | The test passed.
# `-----------------------------
# RUN: at line 6
env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=1 ONEAPI_DEVICE_SELECTOR="level_zero:*" env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# executed command: env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=1 'ONEAPI_DEVICE_SELECTOR=level_zero:*' env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# .---command stdout------------
# | The test passed.
# `-----------------------------
# RUN: at line 7
env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=2 ONEAPI_DEVICE_SELECTOR="level_zero:*" env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# executed command: env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=2 'ONEAPI_DEVICE_SELECTOR=level_zero:*' env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# .---command stdout------------
# | The test passed.
# `-----------------------------
# RUN: at line 8
env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=3 ONEAPI_DEVICE_SELECTOR="level_zero:*" env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# executed command: env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 SYCL_PI_LEVEL_ZERO_BATCH_SIZE=3 'ONEAPI_DEVICE_SELECTOR=level_zero:*' env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/DiscardEvents/Output/discard_events_l0_inorder.cpp.tmp.out
# .---command stderr------------
# | discard_events_l0_inorder.cpp.tmp.out: /__w/llvm/llvm/llvm/sycl/test-e2e/DiscardEvents/discard_events_l0_inorder.cpp:137: void RunCalculation(sycl::queue, sycl::usm::alloc): Assertion `vec1[i] == expected' failed.
# `-----------------------------
# error: command failed with exit status: -6

--

```

**Comment by KseniyaTikhomirova** [comment]
> Struggling to reproduce this with a local clang-19 build on Ubuntu 22.04 due to compile errors:
> 
> ```
> /home/benie/Projects/intel/llvm/build-clang-r/include/sycl/vector.hpp:2094:18: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
>  2094 |     Tmp.template load(offset, ptr);
>       |                  ^
> In file included from /home/benie/Projects/intel/llvm/sycl/source/backend/level_zero.cpp:14:
> In file included from /home/benie/Projects/intel/llvm/build-clang-r/include/sycl/sycl.hpp:53:
> /home/benie/Projects/intel/llvm/build-clang-r/include/sycl/reduction.hpp:1280:28: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
>  1280 |           Reducer.template atomic_combine(&Out[0]);
>       |                            ^
> /home/benie/Projects/intel/llvm/build-clang-r/include/sycl/reduction.hpp:1575:25: warning: comparison of integers of different signs: 'int' and 'const size_t' (aka 'const unsigned long') [-Wsign-compare]
>  1575 |             ++NFinished == NWorkGroups && NWorkGroups > 1;
>       |             ~~~~~~~~~~~ ^  ~~~~~~~~~~~
> ```
> 
> Is this a know issue?
> 
> Edit: I've learned that the post-commit uses the nightly DPC++ build rather than the clang-19 release. My local config was using the latest packages from apt.llvm.org rather than a nightly.

Hi, do you have any updates on this?

**Comment by kbenzie** [comment]
@KseniyaTikhomirova my apologies, no. I've been consumed by the Removing PI work.

**Comment by kbenzie** [comment]
I've reassigned this to @omarahmed1111 to investigate.

**Comment by kbenzie** [comment]
The test has been reenabled, closing this.
