### PR TITLE
[SYCL] Align sub-group implementation and docs

### PR DESCRIPTION
**Pull request by Pennycook**
- Deprecate two-input shuffles
- Fix linear_id type (size_t => uint32_t)
- Add linear ID queries
- Remove fence_space from barrier

Signed-off-by: John Pennycook <john.pennycook@intel.com>

---

Brings the sub-group implementation closer in line with the specification update from https://github.com/intel/llvm/pull/1565.  Includes some minor refactoring to simplify the implementation of requested features (e.g. https://github.com/intel/llvm/issues/1885 and https://github.com/intel/llvm/issues/1916).

### CODE REVIEW

**Comment by Pennycook** [comment]
@bader Could you please take a look at the failing tests for me?  I can't see how the failure relates to these changes.

**Comment by bader** [comment]
> @bader Could you please take a look at the failing tests for me? I can't see how the failure relates to these changes.

I think these failures are caused by your changes:

D:\BuildBot\Product_worker_intel\sycl-win-x64-pr\llvm.src\sycl\include\CL/sycl/intel/sub_group.hpp(281): error C2491: 'cl::sycl::intel::sub_group::shuffle': definition of dllimport function not allowed
D:\BuildBot\Product_worker_intel\sycl-win-x64-pr\llvm.src\sycl\include\CL/sycl/intel/sub_group.hpp(295): error C2491: 'cl::sycl::intel::sub_group::shuffle_down': definition of dllimport function not allowed
D:\BuildBot\Product_worker_intel\sycl-win-x64-pr\llvm.src\sycl\include\CL/sycl/intel/sub_group.hpp(309): error C2491: 'cl::sycl::intel::sub_group::shuffle_up': definition of dllimport function not allowed

If you think internal testing failures are not related to your patch, please, file a bug report.

**Comment by Pennycook** [comment]
> I think these failures are caused by your changes:

Sorry, you're right.  I was focusing on the traceback and somehow missed those three lines.  Thanks for the help!

**Comment by Pennycook** [comment]
@alexey-bataev: The failures seem related to your change in 12805544848a37e009cd1e5c67942930d70f83e2, which replaced `__SYCL_DEPRECATED__` with `__SYCL_EXPORT_DEPRECATED`.  This patch deprecates three new functions, which correspond to the three build failures on Windows.

Have I made a mistake here, or is there something wrong with using `__SYCL_EXPORT_DEPRECATED` in this header?  I'm not very familiar with compiling for Windows, so I'm not sure why defining these three functions as `dllimport` is problematic.

**Comment by alexey-bataev** [comment]
> @alexey-bataev: The failures seem related to your change in [1280554](https://github.com/intel/llvm/commit/12805544848a37e009cd1e5c67942930d70f83e2), which replaced `__SYCL_DEPRECATED__` with `__SYCL_EXPORT_DEPRECATED`. This patch deprecates three new functions, which correspond to the three build failures on Windows.
> 
> Have I made a mistake here, or is there something wrong with using `__SYCL_EXPORT_DEPRECATED` in this header? I'm not very familiar with compiling for Windows, so I'm not sure why defining these three functions as `dllimport` is problematic.

The author is Alexander Batashev, not Alexey Bataev.

**Comment by bader** [comment]
> > @alexey-bataev: The failures seem related to your change in [1280554](https://github.com/intel/llvm/commit/12805544848a37e009cd1e5c67942930d70f83e2), which replaced `__SYCL_DEPRECATED__` with `__SYCL_EXPORT_DEPRECATED`. This patch deprecates three new functions, which correspond to the three build failures on Windows.
> > Have I made a mistake here, or is there something wrong with using `__SYCL_EXPORT_DEPRECATED` in this header? I'm not very familiar with compiling for Windows, so I'm not sure why defining these three functions as `dllimport` is problematic.
> 
> The author is Alexander Batashev, not Alexey Bataev.

I've updated the account id to @alexbatashev in the original comment. Sorry for inconvenience.

**Comment by Pennycook** [comment]
Sorry about the mix-up.

**Comment by jbrodman** [comment]
The comp fails seem like we need to bring back __SYCL_DEPRECATED.

__SYCL_EXPORT_DEPRECATED adding __dllimport is breaking things.

I'm fine with going ahead with that.

**Comment by Pennycook** [comment]
> The comp fails seem like we need to bring back __SYCL_DEPRECATED.

Thanks, @jbrodman.  I've reintroduced `__SYCL_DEPRECATED` in 90d5156.

**Comment by alexbatashev** [comment]
> @alexbatashev : The failures seem related to your change in [1280554](https://github.com/intel/llvm/commit/12805544848a37e009cd1e5c67942930d70f83e2), which replaced `__SYCL_DEPRECATED__` with `__SYCL_EXPORT_DEPRECATED`. This patch deprecates three new functions, which correspond to the three build failures on Windows.
> 
> Have I made a mistake here, or is there something wrong with using `__SYCL_EXPORT_DEPRECATED` in this header? I'm not very familiar with compiling for Windows, so I'm not sure why defining these three functions as `dllimport` is problematic.

The original `__SYCL_DEPRECATED__` was removed, because there was no use for it. @jbrodman's answer is correct.

**Comment by vladimirlaz** [comment]
please resolve conflict.

**Comment by vladimirlaz** [comment]
One more conflict in place...

**Comment by Pennycook** [comment]
Removing the sub-group collectives is leading to CI failures, so I've put them back in for now to help us close this PR.  We should revisit and remove the deprecated functions later.

**Comment by Pennycook** [comment]
Really sorry @AlexeySachkov; the previous commit didn't include all of my local changes, and I didn't catch it until buildbot failed.  To save you from having to review this over and over, I'll ping you when the tests have passed.

**Comment by Pennycook** [comment]
@AlexeySachkov, @vladimirlaz: The tests all passed this time, so I think this is ready for merge.  Thanks for your help with this.
