### ISSUE TITLE
[SYCL][CUDA] Build issue with CUPTI header for CUDA trace

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#17481]
### Describe the bug

I was trying to build with CUDA 12.6.1 and was seeing some error with cupti.h headers not found.
```bash
/home/abagusetty/today/llvm/sycl/tools/sycl-trace/cuda_trace_collector.cpp:17:10: fatal error: cupti.h: No such file or directory
   17 | #include <cupti.h>
      |          ^~~~~~~~~
```

Though my CMakeCache.txt was successfully discovering the CUPTI library
```bash
CMakeCache.txt:706:CUDAToolkit_CUPTI_INCLUDE_DIR:PATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/include
CMakeCache.txt:778:CUDA_cupti_LIBRARY:FILEPATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/lib64/libcupti.so
CMakeCache.txt:781:CUDA_cupti_static_LIBRARY:FILEPATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/lib64/libcupti_static.a
CMakeCache.txt:904:CUDA_nvperf_host_LIBRARY:FILEPATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/lib64/libnvperf_host.so
CMakeCache.txt:907:CUDA_nvperf_host_static_LIBRARY:FILEPATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/lib64/libnvperf_host_static.a
CMakeCache.txt:910:CUDA_nvperf_target_LIBRARY:FILEPATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/lib64/libnvperf_target.so
CMakeCache.txt:928:CUDA_pcsamplingutil_LIBRARY:FILEPATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/lib64/libpcsamplingutil.so
CMakeCache.txt:1140:GEN_CUDA_META_H_DIR:PATH=/soft/compilers/cudatoolkit/cuda-12.6.1/extras/CUPTI/include
CMakeCache.txt:3429://ADVANCED property for variable: CUDAToolkit_CUPTI_INCLUDE_DIR
CMakeCache.txt:3430:CUDAToolkit_CUPTI_INCLUDE_DIR-ADVANCED:INTERNAL=1

```

**Comment by bader** [comment]
Most likely https://github.com/intel/llvm/pull/17457 fixes this issue.

**Comment by abagusetty** [comment]
Great! Thanks the changes fixed the issue
