### ISSUE TITLE
DPC++ fails to compile math_builtin_api test from CTS.

### ISSUE THREAD

**Issue by bader** [intel/llvm#7950]
Post-commit validation detected a regression in the job validating DPC++ using conformance test suite.

```
tests/math_builtin_api/math_builtin_integer.cpp:5875:48: error: no matching function for call to 'clamp'
        sycl_cts::resultRef<sycl::char2> ref = reference::clamp(inputData_0,inputData_1,inputData_2);
                                               ^~~~~~~~~~~~~~~~
/__w/llvm/llvm/khronos_sycl_cts/tests/math_builtin_api/../../util/math_reference.h:246:46: note: candidate template ignored: deduced conflicting types for parameter 'T' ('sycl::char2' (aka 'vec<signed char, 2>') vs. 'char')
template <typename T> sycl_cts::resultRef<T> clamp(T v, T minv, T maxv) {
                                             ^
/__w/llvm/llvm/khronos_sycl_cts/tests/math_builtin_api/../../util/math_reference.h:260:38: note: candidate template ignored: deduced conflicting types for parameter 'T' ('signed char' vs. 'char')
sycl_cts::resultRef<sycl::vec<T, N>> clamp(sycl::vec<T, N> a, T b,
                                     ^
/__w/llvm/llvm/khronos_sycl_cts/tests/math_builtin_api/../../util/math_reference.h:254:1: note: candidate template ignored: could not match 'sycl::vec<T, N>' against 'char'
clamp(sycl::vec<T, N> a, sycl::vec<T, N> b, sycl::vec<T, N> c) {
^
```

This seems to be caused by https://github.com/intel/llvm/commit/1299e21c883616aedd48495f77429f3d235cfaa4 and/or https://github.com/intel/llvm/commit/791ac603d2c56cd9af0042f88c30b310365781fd. 
https://github.com/intel/llvm/commit/e98d732406cc4ba9734cfd8ece96f6d19ddf7267 and https://github.com/intel/llvm/commit/18f2cdab1fd35b071d670fe3059c563e77ad185f doesn't help.

I'm going to disable `math_builtin_api` test in post-commit, while @AlexeySachkov is working on a fix. Please, do not forget to enable this test back.

**Comment by bader** [comment]
@steffenlarsen, does https://github.com/KhronosGroup/SYCL-CTS/pull/462 fix this issue?

**Comment by bader** [comment]
https://github.com/intel/llvm/pull/7951 disabled the test in CI.
Please, enable it back when the issue is fixed.

**Comment by AlexeySachkov** [comment]
@steffenlarsen, can we now close this one?

**Comment by steffenlarsen** [comment]
> @steffenlarsen, can we now close this one?

I believe so! Thanks for reminding me.

**Comment by hvdijk** [comment]
Hi, this issue had "Please, do not forget to enable this test back" in it but it seems that it was never re-enabled? In https://github.com/intel/llvm/actions/runs/8043071758/job/21964904942 I see that `test_math_builtin_api` does not get run, and in `devops/cts_exclude_filter` I see that this is still excluded.

On our end, we are getting different new `test_math_builtin_api` failures. It would be useful if this could also be run on your end, because if it passes on your end, we're doing something wrong, and if it fails on your end, it will highlight that there is an issue.

**Comment by steffenlarsen** [comment]
We should be able to enable all the CTS tests again, though I don't know if any of them were disabled due to time constraints. I know some of the categories can be a little heavy compile-time wise. @bader & @aelovikov-intel - What is the best way to test this?

**Comment by AlexeySachkov** [comment]
Tagging @KornevNikita, who is currently working on enabling more CTS tests on a nightly basis

**Comment by KornevNikita** [comment]
Hi all, I'm going to enable almost all tests (except few that require a lot of time to run), just need some time to test if we can afford it:)

**Comment by coldav** [comment]
> Hi all, I'm going to enable almost all tests (except few that require a lot of time to run), just need some time to test if we can afford it:)

If it helps we see failures in math_builtin_float_base/float_double/integer, which we don't think is specific to our target.

**Comment by KornevNikita** [comment]
> Hi, this issue had "Please, do not forget to enable this test back" in it but it seems that it was never re-enabled? In https://github.com/intel/llvm/actions/runs/8043071758/job/21964904942 I see that `test_math_builtin_api` does not get run, and in `devops/cts_exclude_filter` I see that this is still excluded.
> 
> On our end, we are getting different new `test_math_builtin_api` failures. It would be useful if this could also be run on your end, because if it passes on your end, we're doing something wrong, and if it fails on your end, it will highlight that there is an issue.

Hi, finally extended the set of suites, so we're [running it](https://github.com/intel/llvm/actions/runs/8274840200/job/22670317294) now and you can see that it passes.
