### PR TITLE
[SYCL] Fix CTAD-related issue with std::lock_guard

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This patch fixes post-commit failure introduced in https://github.com/intel/llvm/pull/7468:

```
/Users/runner/work/llvm/llvm/src/sycl/source/detail/program_manager/program_manager.cpp:1324:9: error: 'lock_guard' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
        std::lock_guard HostPipesGuard(m_HostPipesMutex);
        ^
```

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]

**Comment by steffenlarsen** [comment]
Failed Tests (1):
  SYCL :: AtomicRef/atomic_memory_order_acq_rel.cpp
Being disabled in https://github.com/intel/llvm/pull/8885.

Failure in Jenkins precommit is an infrastructure problem and is unrelated.
