### ISSUE TITLE
SYCL/SubGroup/shuffle_fp64.cpp test in intel/llvm-test-suite fails for CUDA backend

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#8516]
The SYCL/SubGroup/shuffle_fp64.cpp test in [intel/llvm-test-suite](https://github.com/intel/llvm-test-suite) fails after https://github.com/intel/llvm-test-suite/pull/1618 for the CUDA backend with errors like

```
  .../include/sycl/detail/spirv.hpp:680:17: error: SYCL kernel cannot call an undefined function without SYCL_EXTERNAL attribute
      result[s] = SubgroupShuffleDown(x[s], delta);
                  ^
  .../include/sycl/detail/spirv.hpp:611:27: note: 'SubgroupShuffleDown<double>' declared here
  EnableIfGenericShuffle<T> SubgroupShuffleDown(T x, id<1> local_id);
                            ^
  .../include/sycl/detail/spirv.hpp:677:26: note: called by 'SubgroupShuffleDown<sycl::vec<double, 16>>'
  EnableIfVectorShuffle<T> SubgroupShuffleDown(T x, uint32_t delta) {
```

See logs on https://github.com/intel/llvm/pull/8425 for more information.

**Comment by GeorgeWeb** [comment]
Hey @steffenlarsen :wave: 

#8614 fixes this.

```
georgi@devpc-4194:~/workspaces/forks/llvm-test-suite/build$ /usr/bin/python3.10 \
/home/georgi/workspaces/dpcpp/llvm/build/./bin/llvm-lit \
-sv --param sycl_be=cuda --param target_devices=gpu \
~/workspaces/forks/llvm-test-suite/build/SYCL/SubGroup/shuffle_fp64.cpp
llvm-lit: /home/georgi/workspaces/forks/llvm-test-suite/SYCL/lit.cfg.py:235: note: Backend: ext_oneapi_cuda

Testing Time: 2.75s
  Passed: 1

2 warning(s) in tests
```

Will open a PR for re-enabling the test, once the fix gets merged.

**Comment by steffenlarsen** [comment]
Fixed by https://github.com/intel/llvm/pull/8614.
